# -*- coding: utf-8 -*-
"""
Created on Thu Nov  8 21:25:16 2018

@author: FoolPepper
"""

RAW_DATA_OPERA_TRAIN = "../CleanedData/op_train_deal.csv"
RAW_DATA_TRANSAC_TRAIN = "../CleanedData/trans_train_deal.csv"
RAW_DATA_LABEL_TRAIN = "../CleanedData/tag_train_new.csv"

RAW_DATA_OPERA_TEST = "../CleanedData/op_test_deal.csv"
RAW_DATA_TRANSAC_TEST = "../CleanedData/trans_test_deal.csv"
RAW_DATA_LABEL_TEST = "../CleanedData/submit_example.csv"


PRE_DATA_OPERA_TRAIN = "../preFeature/0_opera_train.csv"
PRE_DATA_TRANSAC_TRAIN = "../preFeature/0_transac_train.csv"


PRE_DATA_OPERA_TEST = "../preFeature/0_opera_test.csv"
PRE_DATA_TRANSAC_TEST = "../preFeature/0_transac_test.csv"

NEW_RAW_FEATURE_OPERA_TRAIN = "../preFeature/1_new_opera_train.csv"
NEW_RAW_FEATURE_OPERA_TEST = "../preFeature/1_new_opera_test.csv"

NEW_RAW_FEATURE_TRANSAC_TRAIN = "../preFeature/1_new_transac_train.csv"
NEW_RAW_FEATURE_TRANSAC_TEST = "../preFeature/1_new_transac_test.csv"


FEATURE_TRAIN = "../Feature/ss1_train_clean.csv"
FEATURE_TEST = "../Feature/ss1_test_clean.csv"

#OUTPUT_DATA = "../Submit/"


OPERA_DAY_UID_FEATURE = ["os", "version", "device1", "device2", 
                         "device_code1", "device_code2", "device_code3", 
                         "mac1", "ip1", "ip2", "mac2", "ip1_sub",
                         "ip2_sub"]

OPERA_DAY_HOUR_UID_FEATURE = ["os", "version", "device1", "device2", 
                              "device_code1", "device_code2", "device_code3", 
                              "mac1", "ip1", "ip2", "mac2", "ip1_sub",
                              "ip2_sub"]

OPERA_DAT_HOUR_ITEM_FEATURE = ["device1", "device2", "mac1", "device_code1", 
                               "device_code2", "device_code3", "ip1", "ip2", 
                               "mac2", "ip1_sub", "ip2_sub", "geo_code"]


OPERA_FEATURE_COLUMNS = ['mode', 'success', 'time', 'os']


OPERA_FEATURE_OBJECT = ['mode', 'time', 'os','version', 'device_type']

OPERA_FEATURE_OBJECT_UNIQUE = ['device1', 'device2', 
                               'device_code1', 'device_code2', 'mac1',
                               'mac2', 'ip1', 'ip2', 'wifi', 'geo_code', 'ip1_sub', 
                               'ip2_sub', "day_hour_UID_ip2_unique", "day_hour_UID_device_code3_unique", 
                               "day_UID_device_code1_unique", "day_UID_version_unique"]

OPERA_FEATURE_NOT_OBJECT_MEAN = ['day_hour_UID_device2_unique', 
                                 'day_hour_UID_device_code2_unique',
                                 'day_hour_UID_mac1_unique',
                                 'day_hour_UID_mac2_unique', 
                                 "day_UID_ip1_sub_unique",
                                 'day_UID_mac1_unique', 
                                 'day_UID_ip1_unique',
                                 "day_UID_device2_unique",
                                 'day', 
                                 'Hour', 
                                 'Minute', 
                                 'Second', 
                                 'version_num', 
                                 'mode_unique', 
                                 'device1_UID_unique', 
                                 'device2_UID_unique',
                                 'device3_UID_unique', 
                                 'wifi_device1_unique', 
                                 'wifi_device2_unique', 
                                 'wifi_device3_unique', 
                                 'wifi_geo_code_unique', 
                                 'wifi_mac2_unique',
                                 'mac1_UID_unique',
                                 'mac2_UID_unique', 
                                 'ip1_sub_UID_unique', 
                                 'ip2_sub_UID_unique',
                                 'geo_code_device1_unique', 
                                 'geo_code_device2_unique',
                                 'geo_code_device3_unique', 
                                 'geo_code_UID_unique',
                                 'geo_code_wifi_UID_unique', 
                                 'geo_code_wifi_device_code1_unique',
                                 'geo_code_wifi_device_code2_unique',
                                 'geo_code_wifi_device_code3_unique', 
                                 'mode_UID_count',
                                 'mode_UID_success_count',
                                 'Hour_mode_UID_count',
                                 'Hour_mode_UID_success_count', 
                                 'day_UID_os_unique',
                                 'day_UID_device_code2_unique',
                                 'day_UID_mac2_unique', 
                                 'day_hour_device1_UID_unique', 
                                 'day_hour_device2_UID_unique',
                                 'day_hour_mac1_UID_unique',
                                 'day_hour_device_code2_UID_unique', 
                                 'day_hour_device_code3_UID_unique',
                                 'day_hour_ip1_UID_unique', 
                                 'day_hour_ip2_UID_unique',
                                 'day_hour_mac2_UID_unique', 
                                 'day_hour_ip1_sub_UID_unique',
                                 'day_hour_geo_code_UID_unique', 
                                 'day_hour_version_geo_code_unique',
                                 'day_hour_device1_geo_code_unique',
                                 'day_hour_device2_geo_code_unique',
                                 'day_hour_device_code2_geo_code_unique',
                                 'day_hour_device_code3_geo_code_unique',
                                 'day_hour_mac1_geo_code_unique',
                                 'day_hour_ip1_geo_code_unique',
                                 'day_hour_ip2_geo_code_unique',
                                 'day_hour_mac2_geo_code_unique',
                                 "day_hour_os_geo_code_unique",
                                 'day_hour_ip1_sub_geo_code_unique',
                                 'day_os_geo_code_unique',
                                 'day_version_geo_code_unique',
                                 'day_device1_geo_code_unique',
                                 'day_device2_geo_code_unique',
                                 'day_device_code1_geo_code_unique',
                                 'day_device_code2_geo_code_unique',
                                 'day_device_code3_geo_code_unique',
                                 'day_mac1_geo_code_unique',
                                 'day_ip1_geo_code_unique',
                                 'day_ip2_geo_code_unique',
                                 'day_mac2_geo_code_unique',
                                 'day_ip1_sub_geo_code_unique',]

OPERA_FEATURE_NOT_OBJECT = ['day', 'Hour', 'Minute', 'Second', 'version_num', 
                            'mode_unique', 
                            'device1_UID_unique', 'device2_UID_unique',
                            'device3_UID_unique', 'wifi_device1_unique', 
                            'wifi_device2_unique', 'wifi_device3_unique', 
                            'wifi_geo_code_unique', 'wifi_mac2_unique',
                            'ip2_UID_unique', 'hour_device_code1_UID_unique', 'mac1_UID_unique',
                            'mac2_UID_unique', 'ip1_sub_UID_unique', 'ip2_sub_UID_unique',
                            'geo_code_device1_unique', 'geo_code_device2_unique',
                            'geo_code_device3_unique', 'geo_code_UID_unique',
                            'geo_code_wifi_UID_unique', 'geo_code_wifi_device_code1_unique',
                            'geo_code_wifi_device_code2_unique',
                            'geo_code_wifi_device_code3_unique', 'mode_UID_count',
                            'mode_UID_success_count','Hour_mode_UID_count',
                            'Hour_mode_UID_success_count', 'day_UID_os_unique',
                            'day_UID_device_code2_unique',
                            'day_UID_mac2_unique', 
                            'day_hour_UID_os_unique',
                            'day_hour_device1_UID_unique', 'day_hour_device2_UID_unique',
                            'day_hour_mac1_UID_unique', 'day_hour_device_code1_UID_unique',
                            'day_hour_device_code2_UID_unique', 'day_hour_device_code3_UID_unique',
                            'day_hour_ip1_UID_unique', 'day_hour_ip2_UID_unique',
                            'day_hour_mac2_UID_unique', 'day_hour_ip1_sub_UID_unique',
                            'day_hour_ip2_sub_UID_unique', 'day_hour_geo_code_UID_unique',
                            
                            
                             'day_hour_os_geo_code_unique',
 'day_hour_version_geo_code_unique',
 'day_hour_device1_geo_code_unique',
 'day_hour_device2_geo_code_unique',
 'day_hour_device_code1_geo_code_unique',
 'day_hour_device_code2_geo_code_unique',
 'day_hour_device_code3_geo_code_unique',
 'day_hour_mac1_geo_code_unique',
 'day_hour_ip1_geo_code_unique',
 'day_hour_ip2_geo_code_unique',
 'day_hour_mac2_geo_code_unique',
 'day_hour_ip1_sub_geo_code_unique',
 'day_hour_ip2_sub_geo_code_unique',
 'day_os_geo_code_unique',
 'day_version_geo_code_unique',
 'day_device1_geo_code_unique',
 'day_device2_geo_code_unique',
 'day_device_code1_geo_code_unique',
 'day_device_code2_geo_code_unique',
 'day_device_code3_geo_code_unique',
 'day_mac1_geo_code_unique',
 'day_ip1_geo_code_unique',
 'day_ip2_geo_code_unique',
 'day_mac2_geo_code_unique',
 'day_ip1_sub_geo_code_unique',
 'day_ip2_sub_geo_code_unique']



TRANSAC_DAY_HOUR_UID = ["merchant", "code1", "code2", "acc_id1", "device_code1", "device_code2", 
                        "device_code3", "device1", "device2", "mac1", "ip1", "amt_src2", "acc_id2", 
                        "acc_id3", "geo_code", "trans_type2", "market_code", "market_type", 
                        "ip1_sub"]

TRANSAC_DAY_HOUR_MERCHANT = ["acc_id1", "device_code1", "device_code2", "device_code3", 
                             "device1", "mac1", "ip1", "acc_id2", "ip1_sub"]

TRANSAC_DAY_HOUR_ACC = ["acc_id1", "device_code1", "device_code2", "device_code3", 
                        "device1", "mac1", "ip1", "acc_id2", "ip1_sub"]


TRANSAC_FEATURE_OBJECT = ['time', 'amt_src1', 'merchant',"device_type"]

TRANSAC_FEATURE_OBJECT_UNIQUE = ['code1', 'code2', 'trans_type1', 'acc_id1', 'device_code1',
                          'device_code2', 'device_code3', 'device1', 'device2', 'mac1', 'ip1',"amt_src2",
                          "acc_id2", "acc_id3", "geo_code", "market_code", "ip1_sub"]

TRANSAC_FEATURE_NOT_OBJECT = ["bal", "trans_type2", 'Hour',
                              'Minute', 'Second', 'device1_UID_unique',
                              'device2_UID_unique', 'device3_UID_unique', 'market_code_UID_unique',
                              'market_type_mac1_UID_unique',
                              'mac1_acc_id3_UID_unique',
                              'mac1_UID_unique', 'ip1_UID_unique', 'ip1_sub_acc_id3_UID_unique',
                              'geo_code_device1_unique', 'geo_code_device2_unique',
                              'geo_code_device3_unique', 'geo_code_UID_unique',
                              
                              'day_hour_merchant_UID_unique', 'day_hour_code1_UID_unique',
                              'day_hour_code2_UID_unique', 'day_hour_acc_id1_UID_unique',
                              'day_hour_device_code1_UID_unique', 'day_hour_device_code2_UID_unique',
                              'day_hour_device_code3_UID_unique', 'day_hour_device1_UID_unique',
                              'day_hour_device2_UID_unique', 'day_hour_mac1_UID_unique',
                              'day_hour_ip1_UID_unique', 'day_hour_amt_src2_UID_unique',
                              'day_hour_acc_id2_UID_unique', 'day_hour_acc_id3_UID_unique',
                              'day_hour_geo_code_UID_unique', 'day_hour_trans_type2_UID_unique',
                              'day_hour_market_code_UID_unique', 'day_hour_market_type_UID_unique',
                              'day_hour_ip1_sub_UID_unique',              
                              'day_hour_merchant_acc_id1_unique',
                              'day_hour_merchant_device_code1_unique',
                              'day_hour_merchant_device_code2_unique',
                              'day_hour_merchant_device_code3_unique',
                              'day_hour_merchant_device1_unique', 'day_hour_merchant_mac1_unique',
                              'day_hour_merchant_ip1_unique', 'day_hour_merchant_acc_id2_unique',
                              'day_hour_merchant_ip1_sub_unique',
                              'day_hour_code1_acc_id1_unique', 'day_hour_code1_device_code1_unique',
                              'day_hour_code1_device_code2_unique',
                              'day_hour_code1_device_code3_unique', 'day_hour_code1_device1_unique',
                              'day_hour_code1_mac1_unique', 'day_hour_code1_ip1_unique',
                              'day_hour_code1_acc_id2_unique', 'day_hour_code1_ip1_sub_unique',
                              'day_hour_code2_acc_id1_unique',
                              'day_hour_code2_device_code1_unique',
                              'day_hour_code2_device_code2_unique',
                              'day_hour_code2_device_code3_unique', 'day_hour_code2_device1_unique',
                              'day_hour_code2_mac1_unique', 'day_hour_code2_ip1_unique',
                              'day_hour_code2_acc_id2_unique', 'day_hour_code2_ip1_sub_unique', 
                              'day_hour_acc_id3_acc_id1_unique',
                              'day_hour_acc_id3_device_code1_unique',
                              'day_hour_acc_id3_device_code2_unique',
                              'day_hour_acc_id3_device_code3_unique',
                              'day_hour_acc_id3_device1_unique',
                              'day_hour_acc_id3_mac1_unique',
                              'day_hour_acc_id3_ip1_unique',
                              'day_hour_acc_id3_acc_id2_unique',
                              'day_hour_acc_id3_ip1_sub_unique',
 'day_hour_market_code_acc_id1_unique',
 'day_hour_market_code_device_code1_unique',
 'day_hour_market_code_device_code2_unique',
 'day_hour_market_code_device_code3_unique',
 'day_hour_market_code_device1_unique',
 'day_hour_market_code_mac1_unique',
 'day_hour_market_code_ip1_unique',
 'day_hour_market_code_acc_id2_unique',
 'day_hour_market_code_ip1_sub_unique', 
 
 
  'day_hour_market_merchant_trans_amt_sum',
 'day_hour_market_code1_trans_amt_sum',
 'day_hour_market_code2_trans_amt_sum',
 'day_hour_market_UID_trans_amt_sum',
 'day_hour_market_acc_id1_trans_amt_sum',
 'day_hour_market_device_code1_trans_amt_sum',
 'day_hour_market_device_code2_trans_amt_sum',
 'day_hour_market_device_code3_trans_amt_sum',
 'day_hour_market_mac1_trans_amt_sum',
 'day_hour_market_ip1_sub_trans_amt_sum',
 'day_hour_market_ip1_trans_amt_sum',
 'day_hour_market_UID_trans_amt_count',
 'day_hour_market_acc_id1_trans_amt_count',
 'day_hour_market_device_code1_trans_amt_count',
 'day_hour_market_device_code2_trans_amt_count',
 'day_hour_market_device_code3_trans_amt_count',
 'day_hour_market_mac1_trans_amt_count',
 'day_hour_market_ip1_sub_trans_amt_count',
 'day_hour_market_ip1_trans_amt_count',
 'day_hour_market_code2_trans_amt_count',
 
 
 
 'day_market_merchant_trans_amt_sum',
 'day_market_code1_trans_amt_sum',
 'day_market_code2_trans_amt_sum',
 'day_market_UID_trans_amt_sum',
 'day_market_acc_id1_trans_amt_sum',
 'day_market_device_code1_trans_amt_sum',
 'day_market_device_code2_trans_amt_sum',
 'day_market_device_code3_trans_amt_sum',
 'day_market_mac1_trans_amt_sum',
 'day_market_ip1_sub_trans_amt_sum',
 'day_market_ip1_trans_amt_sum',
 'day_market_UID_trans_amt_count',
 'day_market_acc_id1_trans_amt_count',
 'day_market_device_code1_trans_amt_count',
 'day_market_device_code2_trans_amt_count',
 'day_market_device_code3_trans_amt_count',
 'day_market_mac1_trans_amt_count',
 'day_market_ip1_sub_trans_amt_count',
 'day_market_ip1_trans_amt_count',
 'day_market_code2_trans_amt_count',
 
 
 
  'day_three_hour_market_UID_trans_amt_count',
 'day_three_hour_market_acc_id1_trans_amt_count',
 'day_three_hour_market_device_code1_trans_amt_count',
 'day_three_hour_market_device_code2_trans_amt_count',
 'day_three_hour_market_device_code3_trans_amt_count',
 'day_three_hour_market_mac1_trans_amt_count',
 'day_three_hour_market_ip1_sub_trans_amt_count',
 'day_three_hour_market_ip1_trans_amt_count',
 'day_three_hour_market_code2_trans_amt_count',
 'day_three_hour_market_merchant_trans_amt_sum',
 'day_three_hour_market_code1_trans_amt_sum',
 'day_three_hour_market_code2_trans_amt_sum',
 'day_three_hour_market_UID_trans_amt_sum',
 'day_three_hour_market_acc_id1_trans_amt_sum',
 'day_three_hour_market_device_code1_trans_amt_sum',
 'day_three_hour_market_device_code2_trans_amt_sum',
 'day_three_hour_market_device_code3_trans_amt_sum',
 'day_three_hour_market_mac1_trans_amt_sum',
 'day_three_hour_market_ip1_sub_trans_amt_sum',
 'day_three_hour_market_ip1_trans_amt_sum',]

TRANSAC_FEATURE_NOT_OBJECT_MEAN = ["trans_type2", 
                                   'Hour',
                                   'Minute', 
                                   'Second',
                                   'device2_UID_unique', 
                                   'market_code_UID_unique',
                                   'ip1_UID_unique', 
                                   'ip1_sub_acc_id3_UID_unique',
                                   'geo_code_device1_unique', 
                                   'geo_code_device2_unique',
                                   'geo_code_device3_unique', 
                                   'geo_code_UID_unique',
                                   'day_hour_merchant_UID_unique', 
                                   'day_hour_acc_id1_UID_unique',
                                   'day_hour_device1_UID_unique',
                                   'day_hour_device2_UID_unique',
                                   'day_hour_ip1_UID_unique', 
                                   'day_hour_amt_src2_UID_unique',
                                   'day_hour_geo_code_UID_unique',
                                   'day_hour_ip1_sub_UID_unique',              
                                   'day_hour_merchant_acc_id1_unique',
                                   'day_hour_merchant_device_code1_unique',
                                   'day_hour_merchant_device_code2_unique',
                                   'day_hour_merchant_device1_unique', 
                                   'day_hour_merchant_mac1_unique',
                                   'day_hour_merchant_ip1_unique',
                                   'day_hour_code1_acc_id2_unique', 
                                   'day_hour_code2_device_code3_unique', 
                                   'day_hour_code2_acc_id2_unique', 
                                   'day_hour_acc_id3_device1_unique',
                                   'day_hour_acc_id3_acc_id2_unique',
                                   'day_hour_market_merchant_trans_amt_sum',
                                   'day_hour_market_code1_trans_amt_sum',
                                   'day_hour_market_code2_trans_amt_sum',
                                   'day_hour_market_UID_trans_amt_sum',
                                   'day_hour_market_acc_id1_trans_amt_sum',   
                                   'day_hour_market_device_code3_trans_amt_sum',
                                   'day_hour_market_ip1_sub_trans_amt_sum',
                                   'day_hour_market_ip1_trans_amt_sum',
                                   'day_hour_market_UID_trans_amt_count',
                                   'day_hour_market_acc_id1_trans_amt_count',
                                   'day_hour_market_ip1_sub_trans_amt_count',
                                   'day_hour_market_ip1_trans_amt_count',
                                   'day_market_merchant_trans_amt_sum',
                                   'day_market_code1_trans_amt_sum',
                                   'day_market_code2_trans_amt_sum',
                                   'day_market_acc_id1_trans_amt_sum',
                                   "day_market_mac1_trans_amt_sum",
                                   "day_market_ip1_sub_trans_amt_sum",
                                   "day_market_ip1_trans_amt_sum",
                                   "day_market_UID_trans_amt_count",
                                   "day_market_acc_id1_trans_amt_count",
                                   "day_market_device_code2_trans_amt_count",
                                   "day_market_device_code3_trans_amt_count",
                                   "day_market_ip1_trans_amt_count",
                                   "day_market_ip1_sub_trans_amt_count",
                                   'day_market_device_code2_trans_amt_sum',
                                   'day_market_device_code3_trans_amt_sum',
                                   'day_market_code2_trans_amt_count',
                                   'day_three_hour_market_acc_id1_trans_amt_count',
                                   'day_three_hour_market_ip1_sub_trans_amt_count',
                                   'day_three_hour_market_ip1_trans_amt_count',
                                   'day_three_hour_market_merchant_trans_amt_sum',
                                   'day_three_hour_market_code1_trans_amt_sum',
                                   'day_three_hour_market_code2_trans_amt_sum',
                                   'day_three_hour_market_acc_id1_trans_amt_sum',
                                   "day_three_hour_market_device_code3_trans_amt_sum",
                                   "day_three_hour_market_ip1_sub_trans_amt_sum",
                                   
 ]

TRANSAC_FEATURE_NOT_OBJECT_MIN = ["bal", "trans_type2", 'Hour',
                              'Minute', 'Second', 'device1_UID_unique',
                              'device2_UID_unique', 'device3_UID_unique', 'market_code_UID_unique',
                              'market_type_mac1_UID_unique',
                              'mac1_acc_id3_UID_unique',
                              'mac1_UID_unique', 'ip1_UID_unique', 'ip1_sub_acc_id3_UID_unique',
                              'geo_code_device1_unique', 'geo_code_device2_unique',
                              'geo_code_device3_unique', 'geo_code_UID_unique',
                              
                              'day_hour_merchant_UID_unique', 'day_hour_code1_UID_unique',
                              'day_hour_code2_UID_unique', 'day_hour_acc_id1_UID_unique',
                              'day_hour_device_code1_UID_unique', 'day_hour_device_code2_UID_unique',
                              'day_hour_device_code3_UID_unique', 'day_hour_device1_UID_unique',
                              'day_hour_device2_UID_unique', 'day_hour_mac1_UID_unique',
                              'day_hour_ip1_UID_unique', 'day_hour_amt_src2_UID_unique',
                              'day_hour_acc_id2_UID_unique', 'day_hour_acc_id3_UID_unique',
                              'day_hour_geo_code_UID_unique', 'day_hour_trans_type2_UID_unique',
                              'day_hour_market_code_UID_unique', 'day_hour_market_type_UID_unique',
                              'day_hour_ip1_sub_UID_unique',              
                              'day_hour_merchant_acc_id1_unique',
                              'day_hour_merchant_device_code1_unique',
                              'day_hour_merchant_device_code2_unique',
                              'day_hour_merchant_device_code3_unique',
                              'day_hour_merchant_device1_unique', 'day_hour_merchant_mac1_unique',
                              'day_hour_merchant_ip1_unique', 'day_hour_merchant_acc_id2_unique',
                              'day_hour_merchant_ip1_sub_unique',
                              'day_hour_code1_acc_id1_unique', 'day_hour_code1_device_code1_unique',
                              'day_hour_code1_device_code2_unique',
                              'day_hour_code1_device_code3_unique', 'day_hour_code1_device1_unique',
                              'day_hour_code1_mac1_unique', 'day_hour_code1_ip1_unique',
                              'day_hour_code1_acc_id2_unique', 'day_hour_code1_ip1_sub_unique',
                              'day_hour_code2_acc_id1_unique',
                              'day_hour_code2_device_code1_unique',
                              'day_hour_code2_device_code2_unique',
                              'day_hour_code2_device_code3_unique', 'day_hour_code2_device1_unique',
                              'day_hour_code2_mac1_unique', 'day_hour_code2_ip1_unique',
                              'day_hour_code2_acc_id2_unique', 'day_hour_code2_ip1_sub_unique', 
                              'day_hour_acc_id3_acc_id1_unique',
                              'day_hour_acc_id3_device_code1_unique',
                              'day_hour_acc_id3_device_code2_unique',
                              'day_hour_acc_id3_device_code3_unique',
                              'day_hour_acc_id3_device1_unique',
                              'day_hour_acc_id3_mac1_unique',
                              'day_hour_acc_id3_ip1_unique',
                              'day_hour_acc_id3_acc_id2_unique',
                              'day_hour_acc_id3_ip1_sub_unique',
 'day_hour_market_code_acc_id1_unique',
 'day_hour_market_code_device_code1_unique',
 'day_hour_market_code_device_code2_unique',
 'day_hour_market_code_device_code3_unique',
 'day_hour_market_code_device1_unique',
 'day_hour_market_code_mac1_unique',
 'day_hour_market_code_ip1_unique',
 'day_hour_market_code_acc_id2_unique',
 'day_hour_market_code_ip1_sub_unique', 
 
 
  'day_hour_market_merchant_trans_amt_sum',
 'day_hour_market_code1_trans_amt_sum',
 'day_hour_market_code2_trans_amt_sum',
 'day_hour_market_UID_trans_amt_sum',
 'day_hour_market_acc_id1_trans_amt_sum',
 'day_hour_market_device_code1_trans_amt_sum',
 'day_hour_market_device_code2_trans_amt_sum',
 'day_hour_market_device_code3_trans_amt_sum',
 'day_hour_market_mac1_trans_amt_sum',
 'day_hour_market_ip1_sub_trans_amt_sum',
 'day_hour_market_ip1_trans_amt_sum',
 'day_hour_market_UID_trans_amt_count',
 'day_hour_market_acc_id1_trans_amt_count',
 'day_hour_market_device_code1_trans_amt_count',
 'day_hour_market_device_code2_trans_amt_count',
 'day_hour_market_device_code3_trans_amt_count',
 'day_hour_market_mac1_trans_amt_count',
 'day_hour_market_ip1_sub_trans_amt_count',
 'day_hour_market_ip1_trans_amt_count',
 'day_hour_market_code2_trans_amt_count',
 
 
 
  'day_market_merchant_trans_amt_sum',
 'day_market_code1_trans_amt_sum',
 'day_market_code2_trans_amt_sum',
 'day_market_UID_trans_amt_sum',
 'day_market_acc_id1_trans_amt_sum',
 'day_market_device_code1_trans_amt_sum',
 'day_market_device_code2_trans_amt_sum',
 'day_market_device_code3_trans_amt_sum',
 'day_market_mac1_trans_amt_sum',
 'day_market_ip1_sub_trans_amt_sum',
 'day_market_ip1_trans_amt_sum',
 'day_market_UID_trans_amt_count',
 'day_market_acc_id1_trans_amt_count',
 'day_market_device_code1_trans_amt_count',
 'day_market_device_code2_trans_amt_count',
 'day_market_device_code3_trans_amt_count',
 'day_market_mac1_trans_amt_count',
 'day_market_ip1_sub_trans_amt_count',
 'day_market_ip1_trans_amt_count',
 'day_market_code2_trans_amt_count',
 
 
 
  'day_three_hour_market_UID_trans_amt_count',
 'day_three_hour_market_acc_id1_trans_amt_count',
 'day_three_hour_market_device_code1_trans_amt_count',
 'day_three_hour_market_device_code2_trans_amt_count',
 'day_three_hour_market_device_code3_trans_amt_count',
 'day_three_hour_market_mac1_trans_amt_count',
 'day_three_hour_market_ip1_sub_trans_amt_count',
 'day_three_hour_market_ip1_trans_amt_count',
 'day_three_hour_market_code2_trans_amt_count',
 'day_three_hour_market_merchant_trans_amt_sum',
 'day_three_hour_market_code1_trans_amt_sum',
 'day_three_hour_market_code2_trans_amt_sum',
 'day_three_hour_market_UID_trans_amt_sum',
 'day_three_hour_market_acc_id1_trans_amt_sum',
 'day_three_hour_market_device_code1_trans_amt_sum',
 'day_three_hour_market_device_code2_trans_amt_sum',
 'day_three_hour_market_device_code3_trans_amt_sum',
 'day_three_hour_market_mac1_trans_amt_sum',
 'day_three_hour_market_ip1_sub_trans_amt_sum',
 'day_three_hour_market_ip1_trans_amt_sum',]

TRANSAC_FEATURE_NOT_OBJECT_STD = ['day_hour_market_merchant_trans_amt_sum',
                                  'day_hour_market_code1_trans_amt_sum', 
                                  'day_market_merchant_trans_amt_sum',
                                  'day_market_code1_trans_amt_sum',
                                  'day_market_code2_trans_amt_sum',
                                  'day_market_UID_trans_amt_sum',
                                  'day_market_acc_id1_trans_amt_sum',
                                  'day_market_device_code1_trans_amt_sum',
                                  'day_market_device_code2_trans_amt_sum',
                                  'day_market_device_code3_trans_amt_sum',
                                  'day_market_mac1_trans_amt_sum',
                                  'day_market_ip1_sub_trans_amt_sum',
                                  'day_market_ip1_trans_amt_sum',
                                  'day_market_UID_trans_amt_count',
                                  'day_market_acc_id1_trans_amt_count',
                                  'day_market_device_code1_trans_amt_count',
                                  'day_market_device_code2_trans_amt_count',
                                  'day_market_device_code3_trans_amt_count',
                                  'day_market_mac1_trans_amt_count',
                                  'day_market_ip1_sub_trans_amt_count',
                                  'day_market_ip1_trans_amt_count',
                                  'day_market_code2_trans_amt_count',
                                  'day_three_hour_market_merchant_trans_amt_sum',
]


FILTER_FEATURE = ['device2_UID_unique_mean_transac',
 'market_code_UID_unique_mean_transac',
 'ip1_UID_unique_mean_transac',
 'ip1_sub_acc_id3_UID_unique_mean_transac',
 'geo_code_device1_unique_mean_transac',
 'geo_code_device2_unique_mean_transac',
 'geo_code_device3_unique_mean_transac',
 'geo_code_UID_unique_mean_transac',
 'day_hour_merchant_UID_unique_mean_transac',
 'day_hour_acc_id1_UID_unique_mean_transac',
 'day_hour_device1_UID_unique_mean_transac',
 'day_hour_device2_UID_unique_mean_transac',
 'day_hour_ip1_UID_unique_mean_transac',
 'day_hour_amt_src2_UID_unique_mean_transac',
 'day_hour_geo_code_UID_unique_mean_transac',
 'day_hour_ip1_sub_UID_unique_mean_transac',
 'day_hour_merchant_acc_id1_unique_mean_transac',
 'day_hour_merchant_device_code1_unique_mean_transac',
 'day_hour_merchant_device_code2_unique_mean_transac',
 'day_hour_merchant_device1_unique_mean_transac',
 'day_hour_merchant_mac1_unique_mean_transac',
 'day_hour_merchant_ip1_unique_mean_transac',
 'day_hour_code1_acc_id2_unique_mean_transac',
 'day_hour_code2_device_code3_unique_mean_transac',
 'day_hour_code2_acc_id2_unique_mean_transac',
 'day_hour_UID_device2_unique_mean_opera',
 'day_hour_UID_device_code2_unique_mean_opera',
 'day_hour_UID_mac1_unique_mean_opera',
 'day_hour_UID_mac2_unique_mean_opera',
 'day_UID_ip1_sub_unique_mean_opera',
 'day_UID_mac1_unique_mean_opera',
 'day_UID_ip1_unique_mean_opera',
 'day_UID_device2_unique_mean_opera',
 'device1_UID_unique_mean_opera',
 'device2_UID_unique_mean_opera',
 'device3_UID_unique_mean_opera',
 'wifi_device1_unique_mean_opera',
 'wifi_device2_unique_mean_opera',
 'wifi_device3_unique_mean_opera',
 'wifi_geo_code_unique_mean_opera',
 'wifi_mac2_unique_mean_opera',
 'mac1_UID_unique_mean_opera',
 'mac2_UID_unique_mean_opera',
 'ip1_sub_UID_unique_mean_opera',
 'geo_code_device1_unique_mean_opera',
 'geo_code_device2_unique_mean_opera',
 'geo_code_device3_unique_mean_opera',
 'geo_code_UID_unique_mean_opera',
 'geo_code_wifi_UID_unique_mean_opera',
 'geo_code_wifi_device_code1_unique_mean_opera',
 'geo_code_wifi_device_code2_unique_mean_opera',
 'geo_code_wifi_device_code3_unique_mean_opera',
 'mode_UID_count_mean_opera',
 'mode_UID_success_count_mean_opera',
 'Hour_mode_UID_count_mean_opera',
 'Hour_mode_UID_success_count_mean_opera',
 'day_UID_os_unique_mean_opera',
 'day_UID_device_code2_unique_mean_opera',
 'day_UID_mac2_unique_mean_opera',
 'day_hour_device1_UID_unique_mean_opera',
 'day_hour_device2_UID_unique_mean_opera',
 'day_hour_mac1_UID_unique_mean_opera',
 'day_hour_device_code2_UID_unique_mean_opera',
 'day_hour_device_code3_UID_unique_mean_opera',
 'day_hour_ip1_UID_unique_mean_opera',
 'day_hour_mac2_UID_unique_mean_opera',
 'day_hour_ip1_sub_UID_unique_mean_opera',
 'day_hour_geo_code_UID_unique_mean_opera',
 'day_hour_acc_id3_device1_unique_mean_transac',
 'day_hour_acc_id3_acc_id2_unique_mean_transac',
 'ip1_UID_unique_max_transac',
 'ip1_sub_acc_id3_UID_unique_max_transac',
 'geo_code_device1_unique_max_transac',
 'geo_code_device2_unique_max_transac',
 'geo_code_device3_unique_max_transac',
 'geo_code_UID_unique_max_transac',
 'day_hour_merchant_UID_unique_max_transac',
 'day_hour_device1_UID_unique_max_transac',
 'day_hour_amt_src2_UID_unique_max_transac',
 'day_hour_geo_code_UID_unique_max_transac',
 'day_hour_merchant_acc_id1_unique_max_transac',
 'day_hour_merchant_device_code1_unique_max_transac',
 'day_hour_merchant_device_code2_unique_max_transac',
 'day_hour_merchant_ip1_unique_max_transac',
 'day_hour_code1_device_code3_unique_max_transac',
 'ip1_sub_acc_id3_UID_unique_min_transac',
 'geo_code_device1_unique_min_transac',
 'geo_code_device2_unique_min_transac',
 'geo_code_device3_unique_min_transac',
 'geo_code_UID_unique_min_transac',
 'day_hour_code1_UID_unique_min_transac',
 'day_hour_acc_id1_UID_unique_min_transac',
 'day_hour_device1_UID_unique_min_transac',
 'day_hour_amt_src2_UID_unique_min_transac',
 'day_hour_geo_code_UID_unique_min_transac',
 'day_hour_trans_type2_UID_unique_min_transac',
 'day_hour_market_code_UID_unique_min_transac',
 'day_hour_market_type_UID_unique_min_transac',
 'day_hour_code1_acc_id1_unique_min_transac',
 'day_hour_code1_acc_id2_unique_min_transac',
 'day_hour_code2_acc_id1_unique_min_transac',
 'day_hour_acc_id3_acc_id1_unique_min_transac',
 'day_hour_acc_id3_device_code2_unique_min_transac',
 'day_hour_acc_id3_mac1_unique_min_transac',
 'day_hour_market_merchant_trans_amt_sum_mean_transac',
 'day_hour_market_code1_trans_amt_sum_mean_transac',
 'day_hour_market_code2_trans_amt_sum_mean_transac',
 'day_hour_market_UID_trans_amt_sum_mean_transac',
 'day_hour_market_acc_id1_trans_amt_sum_mean_transac',
 'day_hour_market_device_code3_trans_amt_sum_mean_transac',
 'day_hour_market_ip1_sub_trans_amt_sum_mean_transac',
 'day_hour_market_ip1_trans_amt_sum_mean_transac',
 'day_hour_market_UID_trans_amt_count_mean_transac',
 'day_hour_market_acc_id1_trans_amt_count_mean_transac',
 'day_hour_market_ip1_sub_trans_amt_count_mean_transac',
 'day_hour_market_ip1_trans_amt_count_mean_transac',
 'day_market_merchant_trans_amt_sum_mean_transac',
 'day_market_code1_trans_amt_sum_mean_transac',
 'day_market_code2_trans_amt_sum_mean_transac',
 'day_market_acc_id1_trans_amt_sum_mean_transac',
 'day_market_device_code3_trans_amt_sum_mean_transac',
 'day_market_mac1_trans_amt_sum_mean_transac',
 'day_market_ip1_sub_trans_amt_sum_mean_transac',
 'day_market_ip1_trans_amt_sum_mean_transac',
 'day_market_UID_trans_amt_count_mean_transac',
 'day_market_acc_id1_trans_amt_count_mean_transac',
 'day_market_device_code2_trans_amt_count_mean_transac',
 'day_market_device_code3_trans_amt_count_mean_transac',
 'day_market_ip1_sub_trans_amt_count_mean_transac',
 'day_market_ip1_trans_amt_count_mean_transac',
 'day_market_code2_trans_amt_count_mean_transac',
 'day_market_merchant_trans_amt_sum_min_transac',
 'day_market_code1_trans_amt_sum_min_transac',
 'day_market_UID_trans_amt_sum_min_transac',
 'day_market_acc_id1_trans_amt_sum_min_transac',
 'day_market_device_code1_trans_amt_sum_min_transac',
 'day_market_ip1_sub_trans_amt_sum_min_transac',
 'day_market_ip1_trans_amt_sum_min_transac',
 'day_market_acc_id1_trans_amt_count_min_transac',
 'day_market_ip1_sub_trans_amt_count_min_transac',
 'day_market_ip1_trans_amt_count_min_transac',
 'day_market_merchant_trans_amt_sum_max_transac',
 'day_market_UID_trans_amt_sum_max_transac',
 'day_market_acc_id1_trans_amt_sum_max_transac',
 'day_market_ip1_sub_trans_amt_sum_max_transac',
 'day_market_ip1_trans_amt_sum_max_transac',
 'day_market_acc_id1_trans_amt_count_max_transac',
 'day_market_ip1_sub_trans_amt_count_max_transac',
 'day_three_hour_market_acc_id1_trans_amt_count_mean_transac',
 'day_three_hour_market_ip1_sub_trans_amt_count_mean_transac',
 'day_three_hour_market_ip1_trans_amt_count_mean_transac',
 'day_three_hour_market_merchant_trans_amt_sum_mean_transac',
 'day_three_hour_market_code1_trans_amt_sum_mean_transac',
 'day_three_hour_market_code2_trans_amt_sum_mean_transac',
 'day_three_hour_market_acc_id1_trans_amt_sum_mean_transac',
 'day_three_hour_market_device_code3_trans_amt_sum_mean_transac',
 'day_three_hour_market_ip1_sub_trans_amt_sum_mean_transac',
 'day_three_hour_market_acc_id1_trans_amt_count_min_transac',
 'day_three_hour_market_code2_trans_amt_count_min_transac',
 'day_three_hour_market_merchant_trans_amt_sum_min_transac',
 'day_three_hour_market_code1_trans_amt_sum_min_transac',
 'day_three_hour_market_code2_trans_amt_sum_min_transac',
 'day_three_hour_market_acc_id1_trans_amt_sum_min_transac',
 'day_three_hour_market_device_code3_trans_amt_sum_min_transac',
 'day_three_hour_market_mac1_trans_amt_sum_min_transac',
 'day_three_hour_market_ip1_sub_trans_amt_sum_min_transac',
 'day_three_hour_market_ip1_trans_amt_sum_min_transac',
 'day_three_hour_market_merchant_trans_amt_sum_max_transac',
 'day_three_hour_market_UID_trans_amt_sum_max_transac',
 'day_three_hour_market_acc_id1_trans_amt_sum_max_transac',
 'day_three_hour_market_device_code3_trans_amt_sum_max_transac',
 'day_three_hour_market_mac1_trans_amt_sum_max_transac',
 'day_three_hour_market_ip1_sub_trans_amt_sum_max_transac',
 'day_three_hour_market_ip1_trans_amt_sum_max_transac',
 'day_hour_os_geo_code_unique_mean_opera',
 'day_hour_version_geo_code_unique_mean_opera',
 'day_hour_device1_geo_code_unique_mean_opera',
 'day_hour_device2_geo_code_unique_mean_opera',
 'day_hour_device_code2_geo_code_unique_mean_opera',
 'day_hour_device_code3_geo_code_unique_mean_opera',
 'day_hour_mac1_geo_code_unique_mean_opera',
 'day_hour_ip1_geo_code_unique_mean_opera',
 'day_hour_mac2_geo_code_unique_mean_opera',
 'day_hour_ip1_sub_geo_code_unique_mean_opera',
 'day_os_geo_code_unique_mean_opera',
 'day_version_geo_code_unique_mean_opera',
 'day_device1_geo_code_unique_mean_opera',
 'day_device2_geo_code_unique_mean_opera',
 'day_device_code1_geo_code_unique_mean_opera',
 'day_device_code2_geo_code_unique_mean_opera',
 'day_device_code3_geo_code_unique_mean_opera',
 'day_mac1_geo_code_unique_mean_opera',
 'day_ip1_geo_code_unique_mean_opera',
 'day_mac2_geo_code_unique_mean_opera',
 'day_ip1_sub_geo_code_unique_mean_opera',
 'day_hour_market_merchant_trans_amt_sum_std_transac',
 'day_hour_market_code1_trans_amt_sum_std_transac',
 'day_market_merchant_trans_amt_sum_std_transac',
 'day_market_code1_trans_amt_sum_std_transac',
 'day_market_code2_trans_amt_sum_std_transac',
 'day_market_UID_trans_amt_sum_std_transac',
 'day_market_acc_id1_trans_amt_sum_std_transac',
 'day_market_device_code1_trans_amt_sum_std_transac',
 'day_market_device_code2_trans_amt_sum_std_transac',
 'day_market_device_code3_trans_amt_sum_std_transac',
 'day_market_mac1_trans_amt_sum_std_transac',
 'day_market_ip1_sub_trans_amt_sum_std_transac',
 'day_market_ip1_trans_amt_sum_std_transac',
 'day_market_UID_trans_amt_count_std_transac',
 'day_market_acc_id1_trans_amt_count_std_transac',
 'day_market_device_code1_trans_amt_count_std_transac',
 'day_market_device_code2_trans_amt_count_std_transac',
 'day_market_device_code3_trans_amt_count_std_transac',
 'day_market_mac1_trans_amt_count_std_transac',
 'day_market_ip1_sub_trans_amt_count_std_transac',
 'day_market_ip1_trans_amt_count_std_transac',
 'day_market_code2_trans_amt_count_std_transac',
 'day_three_hour_market_merchant_trans_amt_sum_std_transac'

]




TEST = [ 'day_wifi_count',
 'day_mac2_count',
 'day_os_count',
 'day_ip2_count',
 'day_wifi_transa_amt_sum',
 'day_mac2_transa_amt_sum',
 'day_os_transa_amt_sum',
 'day_ip2_transa_amt_sum',
 'day_hour_wifi_count',
 'day_hour_mac2_count',
 'day_hour_os_count',
 'day_hour_ip2_count',
 'day_hour_wifi_transa_amt_sum',
 'day_hour_mac2_transa_amt_sum',
 'day_hour_os_transa_amt_sum',
 'day_hour_ip2_transa_amt_sum',
 'day_merchant_UID_unique',
 'day_merchant_UID_count']

USELESS = [ 'day_hour_market_code_acc_id1_unique_min_transac',
       'day_hour_market_code_device_code1_unique_min_transac',
       'day_hour_market_code_device_code2_unique_min_transac',
       'day_hour_market_code_device_code3_unique_min_transac',
       'day_hour_market_code_device1_unique_min_transac',
       'day_hour_market_code_mac1_unique_min_transac',
       'day_hour_market_code_ip1_unique_min_transac',
       'day_hour_market_code_acc_id2_unique_min_transac',
       'day_hour_market_code_ip1_sub_unique_min_transac', 'bal_min_transac']


