# -*- coding: utf-8 -*-

import pandas as pd
import numpy as np


def drop_col_KDE_xx(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    xx_feature_list_3 = []
    xx_feature_list_5 = [] 
    
    xx_feature_list_4 = ['mac1_diff_UID_median_op',
                         'mac1_diff_UID_max_op',
                         'ip1_diff_UID_median_op',
                         'ip1_diff_UID_max_op',
                         'mac2_diff_UID_median_op',
                         'mac2_diff_UID_max_op',
                         'wifi_diff_UID_max_op',
                         'mac1_diff_UID_median_trans',
                         'mac1_diff_UID_max_trans',
                         'ip1_diff_UID_median_trans',
                         'ip1_diff_UID_max_trans']
    
    xx_feature_list_1 = []
    
    xx_feature_list_2 = ['mac2_max_UID_nums_per_second_op',
                         'device2_UID_nums_per_second',
                         'wifi_diff_UID_median_op',
                         'device_code3_diff_UID_max_trans']
    xx_feature_list_6 = []

    drop_list = xx_feature_list_1
    drop_list.extend(xx_feature_list_4)
    #drop_list.extend(cc_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df

def drop_col_KDE_ss1Clean(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    ss1Clean_feature_list_3 = ['day_hour_geo_code_UID_unique_mean_transac',
                         'day_hour_ip1_sub_UID_unique_mean_transac',
                         'mode_UID_count_mean_opera',
                         'mode_UID_success_count_mean_opera',
                         'day_hour_device_code2_UID_unique_mean_opera',
                         'day_hour_ip1_sub_UID_unique_mean_opera',
                         'day_hour_geo_code_UID_unique_mean_opera',
                         'day_hour_geo_code_UID_unique_min_transac',
                         'day_hour_code2_acc_id1_unique_min_transac',
                         'day_hour_market_acc_id1_trans_amt_count_mean_transac',
                         'day_hour_market_ip1_trans_amt_count_mean_transac']

    ss1Clean_feature_list_5 = [] 
    
    ss1Clean_feature_list_4 = ['device2_UID_unique_mean_transac',
                         'market_code_UID_unique_mean_transac',
                         'ip1_UID_unique_mean_transac',
                         'ip1_sub_acc_id3_UID_unique_mean_transac',
                         'day_hour_code1_acc_id2_unique_mean_transac',
                         'day_hour_code2_acc_id2_unique_mean_transac',
                         'day_hour_UID_device2_unique_mean_opera',
                         'day_hour_UID_device_code2_unique_mean_opera',
                         'day_hour_UID_mac1_unique_mean_opera',
                         'day_hour_UID_mac2_unique_mean_opera',
                         'day_UID_ip1_sub_unique_mean_opera',
                         'day_UID_mac1_unique_mean_opera',
                         'day_UID_ip1_unique_mean_opera',
                         'day_UID_device2_unique_mean_opera',
                         'device1_UID_unique_mean_opera',
                         'device2_UID_unique_mean_opera',
                         'ip1_sub_UID_unique_mean_opera',
                         'Hour_mode_UID_count_mean_opera',
                         'Hour_mode_UID_success_count_mean_opera',
                         'day_UID_os_unique_mean_opera',
                         'day_UID_device_code2_unique_mean_opera',
                         'day_hour_device1_UID_unique_mean_opera',
                         'day_hour_device2_UID_unique_mean_opera',
                         'day_hour_mac1_UID_unique_mean_opera',
                         'day_hour_device_code3_UID_unique_mean_opera',
                         'day_hour_mac2_UID_unique_mean_opera',
                         'day_hour_acc_id3_acc_id2_unique_mean_transac',
                         'ip1_UID_unique_max_transac',
                         'ip1_sub_acc_id3_UID_unique_max_transac',
                         'day_hour_merchant_UID_unique_max_transac',
                         'day_hour_device1_UID_unique_max_transac',
                         'day_hour_amt_src2_UID_unique_max_transac',
                         'ip1_sub_acc_id3_UID_unique_min_transac',
                         'geo_code_device1_unique_min_transac',
                         'day_hour_trans_type2_UID_unique_min_transac',
                         'day_hour_market_code_UID_unique_min_transac',
                         'day_hour_market_type_UID_unique_min_transac',
                         'day_hour_acc_id3_acc_id1_unique_min_transac',
                         'day_hour_acc_id3_device_code2_unique_min_transac',
                         'day_hour_acc_id3_mac1_unique_min_transac',
                         'day_market_merchant_trans_amt_sum_mean_transac',
                         'day_market_code1_trans_amt_sum_mean_transac',
                         'day_market_code2_trans_amt_sum_mean_transac',
                         'day_market_acc_id1_trans_amt_sum_mean_transac',
                         'day_market_device_code3_trans_amt_sum_mean_transac',
                         'day_market_mac1_trans_amt_sum_mean_transac',
                         'day_market_ip1_sub_trans_amt_sum_mean_transac',
                         'day_market_ip1_trans_amt_sum_mean_transac',
                         'day_market_acc_id1_trans_amt_count_mean_transac',
                         'day_market_device_code2_trans_amt_count_mean_transac',
                         'day_market_device_code3_trans_amt_count_mean_transac',
                         'day_market_ip1_sub_trans_amt_count_mean_transac',
                         'day_market_ip1_trans_amt_count_mean_transac',
                         'day_market_code2_trans_amt_count_mean_transac',
                         'day_market_merchant_trans_amt_sum_min_transac',
                         'day_market_code1_trans_amt_sum_min_transac',
                         'day_market_UID_trans_amt_sum_min_transac',
                         'day_market_acc_id1_trans_amt_sum_min_transac',
                         'day_market_device_code1_trans_amt_sum_min_transac',
                         'day_market_ip1_sub_trans_amt_sum_min_transac',
                         'day_market_ip1_trans_amt_sum_min_transac',
                         'day_market_acc_id1_trans_amt_count_min_transac',
                         'day_market_ip1_sub_trans_amt_count_min_transac',
                         'day_market_ip1_trans_amt_count_min_transac',
                         'day_market_merchant_trans_amt_sum_max_transac',
                         'day_market_acc_id1_trans_amt_sum_max_transac',
                         'day_market_ip1_sub_trans_amt_sum_max_transac',
                         'day_market_ip1_trans_amt_sum_max_transac',
                         'day_market_acc_id1_trans_amt_count_max_transac',
                         'day_market_ip1_sub_trans_amt_count_max_transac',
                         'day_three_hour_market_acc_id1_trans_amt_count_mean_transac',
                         'day_three_hour_market_mac1_trans_amt_sum_min_transac',
                         'day_three_hour_market_ip1_sub_trans_amt_sum_min_transac',
                         'day_three_hour_market_ip1_trans_amt_sum_min_transac',
                         'day_three_hour_market_merchant_trans_amt_sum_max_transac',
                         'day_three_hour_market_acc_id1_trans_amt_sum_max_transac',
                         'day_three_hour_market_device_code3_trans_amt_sum_max_transac',
                         'day_device_code1_geo_code_unique_mean_opera',
                         'day_market_device_code2_trans_amt_sum_std_transac',
                         'day_market_ip1_sub_trans_amt_sum_std_transac',
                         'day_market_ip1_trans_amt_sum_std_transac',
                         'day_market_acc_id1_trans_amt_count_std_transac',
                         'day_market_device_code1_trans_amt_count_std_transac',
                         'day_market_device_code2_trans_amt_count_std_transac',
                         'day_market_device_code3_trans_amt_count_std_transac',
                         'day_market_mac1_trans_amt_count_std_transac',
                         'day_market_ip1_sub_trans_amt_count_std_transac',
                         'day_market_ip1_trans_amt_count_std_transac',
                         'day_market_code2_trans_amt_count_std_transac']
    
    ss1Clean_feature_list_1 = ['geo_code_device1_unique_mean_transac',
                         'geo_code_device2_unique_mean_transac',
                         'day_hour_merchant_UID_unique_mean_transac',
                         'day_hour_acc_id1_UID_unique_mean_transac',
                         'day_hour_device1_UID_unique_mean_transac',
                         'day_hour_device2_UID_unique_mean_transac',
                         'day_hour_ip1_UID_unique_mean_transac',
                         'day_hour_amt_src2_UID_unique_mean_transac',
                         'day_hour_merchant_acc_id1_unique_mean_transac',
                         'day_hour_merchant_device_code1_unique_mean_transac',
                         'day_hour_merchant_device_code2_unique_mean_transac',
                         'day_hour_merchant_device1_unique_mean_transac',
                         'day_hour_merchant_mac1_unique_mean_transac',
                         'device3_UID_unique_mean_opera',
                         'wifi_device1_unique_mean_opera',
                         'wifi_device2_unique_mean_opera',
                         'wifi_device3_unique_mean_opera',
                         'day_hour_ip1_UID_unique_mean_opera',
                         'day_hour_acc_id3_device1_unique_mean_transac',
                         'geo_code_device1_unique_max_transac',
                         'day_hour_geo_code_UID_unique_max_transac',
                         'day_hour_merchant_acc_id1_unique_max_transac',
                         'day_hour_merchant_device_code1_unique_max_transac',
                         'day_hour_merchant_device_code2_unique_max_transac',
                         'day_hour_merchant_ip1_unique_max_transac',
                         'day_hour_code1_UID_unique_min_transac',
                         'day_hour_acc_id1_UID_unique_min_transac',
                         'day_hour_device1_UID_unique_min_transac',
                         'day_hour_amt_src2_UID_unique_min_transac',
                         'day_hour_code1_acc_id1_unique_min_transac',
                         'day_hour_code1_acc_id2_unique_min_transac',
                         'day_hour_market_merchant_trans_amt_sum_mean_transac',
                         'day_hour_market_code1_trans_amt_sum_mean_transac',
                         'day_hour_market_code2_trans_amt_sum_mean_transac',
                         'day_hour_market_UID_trans_amt_sum_mean_transac',
                         'day_hour_market_acc_id1_trans_amt_sum_mean_transac',
                         'day_hour_market_ip1_sub_trans_amt_sum_mean_transac',
                         'day_hour_market_ip1_trans_amt_sum_mean_transac',
                         'day_hour_market_UID_trans_amt_count_mean_transac',
                         'day_hour_market_ip1_sub_trans_amt_count_mean_transac',
                         'day_market_UID_trans_amt_sum_max_transac',
                         'day_three_hour_market_ip1_sub_trans_amt_count_mean_transac',
                         'day_three_hour_market_ip1_trans_amt_count_mean_transac',
                         'day_three_hour_market_merchant_trans_amt_sum_mean_transac',
                         'day_three_hour_market_code1_trans_amt_sum_mean_transac',
                         'day_three_hour_market_code2_trans_amt_sum_mean_transac',
                         'day_three_hour_market_ip1_sub_trans_amt_sum_mean_transac',
                         'day_three_hour_market_acc_id1_trans_amt_count_min_transac',
                         'day_three_hour_market_code2_trans_amt_count_min_transac',
                         'day_three_hour_market_merchant_trans_amt_sum_min_transac',
                         'day_three_hour_market_code1_trans_amt_sum_min_transac',
                         'day_three_hour_market_code2_trans_amt_sum_min_transac',
                         'day_three_hour_market_UID_trans_amt_sum_max_transac',
                         'day_three_hour_market_mac1_trans_amt_sum_max_transac',
                         'day_three_hour_market_ip1_sub_trans_amt_sum_max_transac',
                         'day_three_hour_market_ip1_trans_amt_sum_max_transac',
                         'day_hour_version_geo_code_unique_mean_opera',
                         'day_hour_device2_geo_code_unique_mean_opera',
                         'day_hour_mac1_geo_code_unique_mean_opera',
                         'day_hour_ip1_geo_code_unique_mean_opera',
                         'day_hour_mac2_geo_code_unique_mean_opera',
                         'day_hour_ip1_sub_geo_code_unique_mean_opera',
                         'day_device2_geo_code_unique_mean_opera',
                         'day_ip1_geo_code_unique_mean_opera',
                         'day_mac2_geo_code_unique_mean_opera',
                         'day_hour_market_merchant_trans_amt_sum_std_transac',
                         'day_hour_market_code1_trans_amt_sum_std_transac',
                         'day_market_merchant_trans_amt_sum_std_transac',
                         'day_market_code2_trans_amt_sum_std_transac',
                         'day_market_UID_trans_amt_sum_std_transac',
                         'day_market_UID_trans_amt_count_std_transac',
                         'day_three_hour_market_merchant_trans_amt_sum_std_transac']
    
    ss1Clean_feature_list_2 = ['geo_code_device3_unique_mean_transac',
                         'geo_code_UID_unique_mean_transac',
                         'day_hour_merchant_ip1_unique_mean_transac',
                         'day_hour_code2_device_code3_unique_mean_transac',
                         'wifi_geo_code_unique_mean_opera',
                         'wifi_mac2_unique_mean_opera',
                         'mac1_UID_unique_mean_opera',
                         'mac2_UID_unique_mean_opera',
                         'geo_code_device1_unique_mean_opera',
                         'geo_code_device2_unique_mean_opera',
                         'geo_code_device3_unique_mean_opera',
                         'geo_code_UID_unique_mean_opera',
                         'geo_code_wifi_UID_unique_mean_opera',
                         'geo_code_wifi_device_code1_unique_mean_opera',
                         'geo_code_wifi_device_code2_unique_mean_opera',
                         'geo_code_wifi_device_code3_unique_mean_opera',
                         'day_UID_mac2_unique_mean_opera',
                         'geo_code_device2_unique_max_transac',
                         'geo_code_UID_unique_max_transac',
                         'day_hour_code1_device_code3_unique_max_transac',
                         'geo_code_device2_unique_min_transac',
                         'geo_code_device3_unique_min_transac',
                         'geo_code_UID_unique_min_transac',
                         'day_hour_market_device_code3_trans_amt_sum_mean_transac',
                         'day_market_UID_trans_amt_count_mean_transac',
                         'day_three_hour_market_acc_id1_trans_amt_sum_mean_transac',
                         'day_three_hour_market_device_code3_trans_amt_sum_mean_transac',
                         'day_three_hour_market_acc_id1_trans_amt_sum_min_transac',
                         'day_hour_os_geo_code_unique_mean_opera',
                         'day_hour_device1_geo_code_unique_mean_opera',
                         'day_hour_device_code3_geo_code_unique_mean_opera',
                         'day_os_geo_code_unique_mean_opera',
                         'day_version_geo_code_unique_mean_opera',
                         'day_device1_geo_code_unique_mean_opera',
                         'day_device_code2_geo_code_unique_mean_opera',
                         'day_device_code3_geo_code_unique_mean_opera',
                         'day_mac1_geo_code_unique_mean_opera',
                         'day_ip1_sub_geo_code_unique_mean_opera',
                         'day_market_code1_trans_amt_sum_std_transac',
                         'day_market_acc_id1_trans_amt_sum_std_transac',
                         'day_market_device_code1_trans_amt_sum_std_transac',
                         'day_market_device_code3_trans_amt_sum_std_transac']
    ss1Clean_feature_list_6 = []

    drop_list = ss1Clean_feature_list_1
    drop_list.extend(ss1Clean_feature_list_4)
    #drop_list.extend(cc_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df


def drop_col_KDE_lyf(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    lyf_feature_list_3 = ['unknownratio_device1_y_lyf',
                         'unknownratio_mac1_y_lyf',
                         'sum_trans_amt_lyf',
                         'unique_trans_type1_lyf',
                         'UID_day_second_merchant_maxnums_lyf',
                         'UID_used_by_meandevice_code1_y_lyf',
                         'UID_used_by_maxdevice_code1_y_lyf',
                         'UID_used_by_meandevice_code2_y_lyf',
                         'UID_used_by_maxdevice_code2_y_lyf',
                         'add_maxdevicecode2_onesratio_ip1_lyf']
    lyf_feature_list_5 = ['UID_day_second_device_code3_maxnums_x_lyf',
                         'UID_day_minute_device_code3_maxnums_y_lyf',
                         'UID_day_second_device_code3_maxnums_y_lyf',
                         'UID_used_by_ones_ratiodevice1_y_lyf',
                         'amt_src1_lyf',
                         'isriskdevice1_lyf'] 
    
    lyf_feature_list_4 = ['OP_n_null_median_lyf',
                         'unknownratio_device_code1_x_lyf',
                         'unknownratio_device_code2_x_lyf',
                         'unknownratio_device_code3_x_lyf',
                         'unknownratio_wifi_lyf',
                         'unique_mode_lyf',
                         'unique_version_lyf',
                         'unique_device2_x_lyf',
                         'unique_device_code1_x_lyf',
                         'unique_device_code2_x_lyf',
                         'UID_day_minute_wifi_maxnums_lyf',
                         'UID_day_second_wifi_maxnums_lyf',
                         'UID_day_minute_ip1_sub_maxnums_lyf',
                         'UID_day_second_ip1_sub_maxnums_lyf',
                         'UID_used_by_meanip1_x_lyf',
                         'UID_used_by_ones_ratiodevice_code1_x_lyf',
                         'UID_used_by_ones_ratiodevice_code2_x_lyf',
                         'uniqueratio_modedevice_code2_lyf',
                         'uniqueratio_modedevice_code3_lyf',
                         'uniqueratio_modemac1_lyf',
                         'uniqueratio_device1mode_lyf',
                         'uniqueratio_modedevice1_lyf',
                         'uniqueratio_modedevice2_lyf',
                         'uniqueratio_wifidevice_code1_lyf',
                         'uniqueratio_device_code3wifi_lyf',
                         'uniqueratio_wifidevice_code3_lyf',
                         'uniqueratio_mac1wifi_lyf',
                         'uniqueratio_wifimac1_lyf',
                         'uniqueratio_device1wifi_lyf',
                         'uniqueratio_device2wifi_lyf',
                         'uniqueratio_wifidevice2_lyf',
                         'unknownratio_device_code3_y_lyf',
                         'max_day_lyf',
                         'min_day_lyf',
                         'mean_day_lyf',
                         'std_day_lyf',
                         'min_trans_amt_lyf',
                         'unique_amt_src1_lyf',
                         'unique_merchant_lyf',
                         'unique_geo_code_y_lyf',
                         'min_trans_type2_lyf',
                         'mean_trans_type2_lyf',
                         'UID_day_minute_device1_maxnums_y_lyf',
                         'UID_day_second_device1_maxnums_y_lyf',
                         'UID_day_minute_device2_maxnums_y_lyf',
                         'UID_day_second_device2_maxnums_y_lyf',
                         'UID_day_minute_ip1_maxnums_y_lyf',
                         'UID_day_second_ip1_maxnums_y_lyf',
                         'UID_used_by_meandevice2_y_lyf',
                         'UID_used_by_maxdevice2_y_lyf',
                         'UID_used_by_meanmac1_y_lyf',
                         'UID_used_by_maxmac1_y_lyf',
                         'UID_used_by_maxip1_y_lyf',
                         'UID_used_by_ones_ratioip1_y_lyf',
                         'UID_used_risk_merchant_lyf',
                         'uniqueratio_device_code1amt_src2_lyf',
                         'uniqueratio_device_code2amt_src2_lyf',
                         'channel_102_lyf',
                         'channel_140_lyf',
                         'is_UID_all_transaction_lyf',
                         'channel_lyf',
                         'day_lyf',
                         'device_code3_lyf',
                         'ip2_lyf',
                         'trans_amt_lyf']
    
    lyf_feature_list_1 = ['unique_mac2_lyf',
                         'unique_geo_code_x_lyf',
                         'unique_ip1_sub_x_lyf',
                         'unique_n_null_lyf',
                         'UID_day_minute_device2_maxnums_x_lyf',
                         'UID_day_minute_mac1_maxnums_x_lyf',
                         'UID_day_minute_device_code3_maxnums_x_lyf',
                         'UID_used_by_meanmac2_lyf',
                         'UID_used_by_maxmac2_lyf',
                         'UID_used_by_ones_ratiomac2_lyf',
                         'UID_used_by_ones_ratiowifi_lyf',
                         'UID_used_by_meanip1_sub_lyf',
                         'UID_used_by_ones_ratioip1_sub_lyf',
                         'unknownratio_acc_id1_lyf',
                         'unknownratio_device2_y_lyf',
                         'unknownratio_ip1_y_lyf',
                         'unknownratio_amt_src2_lyf',
                         'unknownratio_trans_type2_lyf',
                         'unique_channel_lyf',
                         'max_channel_lyf',
                         'unique_day_lyf',
                         'unique_time_y_lyf',
                         'unique_trans_amt_lyf',
                         'max_trans_amt_lyf',
                         'mean_trans_amt_lyf',
                         'unique_code2_lyf',
                         'unique_acc_id1_lyf',
                         'unique_device_code1_y_lyf',
                         'unique_device_code3_y_lyf',
                         'unique_device1_y_lyf',
                         'unique_device2_y_lyf',
                         'unique_mac1_y_lyf',
                         'unique_ip1_y_lyf',
                         'mean_bal_lyf',
                         'unique_amt_src2_lyf',
                         'unique_acc_id3_lyf',
                         'unique_market_code_lyf',
                         'UID_day_second_mac1_maxnums_y_lyf',
                         'uniqueratio_device_code2channel_lyf',
                         'uniqueratio_device_code3channel_lyf',
                         'uniqueratio_device_code1amt_src1_lyf',
                         'uniqueratio_device_code2amt_src1_lyf',
                         'uniqueratio_device_code3amt_src1_lyf']
    
    lyf_feature_list_2 = ['OP_day_var_lyf',
                         'unknownratio_mac2_lyf',
                         'unknownratio_geo_code_x_lyf',
                         'unique_time_x_lyf',
                         'UID_day_minute_mac2_maxnums_lyf',
                         'UID_used_by_meandevice1_x_lyf',
                         'UID_used_by_maxdevice1_x_lyf',
                         'UID_used_by_maxip1_x_lyf',
                         'UID_used_by_ones_ratioip1_x_lyf',
                         'mean_channel_lyf',
                         'max_bal_lyf',
                         'max_trans_type2_lyf',
                         'std_trans_type2_lyf',
                         'UID_day_minute_merchant_maxnums_lyf',
                         'UID_day_minute_acc_id1_maxnums_lyf',
                         'UID_day_second_acc_id1_maxnums_lyf',
                         'UID_used_by_meandevice1_y_lyf',
                         'UID_used_by_maxdevice1_y_lyf',
                         'UID_used_by_ones_ratiodevice_code3_y_lyf',
                         'UID_used_by_meanip1_y_lyf',
                         'uniqueratio_channeldevice_code3_lyf',
                         'uniqueratio_amt_src1device_code2_lyf',
                         'device2_lyf',
                         'geo_code_lyf',
                         'mac1_lyf',
                         'mac2_lyf',
                         'mode_lyf',
                         'os_lyf']
    lyf_feature_list_6 = []

    drop_list = lyf_feature_list_1
    drop_list.extend(lyf_feature_list_4)
    #drop_list.extend(cc_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df

def drop_col_KDE_ss6(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    ss6_feature_list_3 = ['transac_twelve_hour_uid_rank_amp_up',
                         'every_minute_opera_freq_std',
                         'every_minute_opera_freq_var']
    ss6_feature_list_5 = [] 
    
    ss6_feature_list_4 = ['transac_day_mechant_rank_amp_up',
                         'transac_day_code1_rank_amp_up',
                         'transac_day_code1_rank_amp_down',
                         'transac_day_code1_amt_rank_amp_up',
                         'transac_day_code1_amt_rank_amp_down',
                         'ten_minute_opera_freq_mean']
    
    ss6_feature_list_1 = ['transac_twelve_hour_uid_rank_amp_down',
                         'transac_day_mechant_rank_amp_down',
                         'three_hour_geo_rank_amp_up',
                         'three_hour_geo_rank_amp_down',
                         'six_hour_geo_rank_amp_up',
                         'six_hour_geo_rank_amp_down',
                         'every_minute_opera_freq_min',
                         'every_minute_opera_freq_mean',
                         'every_minute_opera_freq_med',
                         'every_minute_amp_up',
                         'every_minute_amp_down',
                         'ten_minute_opera_freq_max',
                         'ten_minute_opera_freq_min',
                         'ten_minute_opera_freq_std',
                         'ten_minute_opera_freq_var',
                         'ten_minute_opera_freq_med',
                         'ten_minute_amp_down']
    
    ss6_feature_list_2 = ['ten_minute_amp_up']
    ss6_feature_list_6 = []

    drop_list = ss6_feature_list_1
    drop_list.extend(ss6_feature_list_4)
    #drop_list.extend(cc_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df
def drop_col_KDE_ss4(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    ss4_feature_list_3 = ['six_hour_uid_rank_max',
                         'six_hour_uid_rank_min',
                         'six_hour_uid_rank_mean',
                         'six_hour_uid_rank_std']

    ss4_feature_list_5 = [] 
    
    ss4_feature_list_4 = []
    
    ss4_feature_list_1 = ['three_hour_geo_rank_max',
                         'three_hour_geo_rank_min',
                         'three_hour_geo_rank_mean',
                         'three_hour_geo_rank_std',
                         'three_hour_geo_rank_var',
                         'three_hour_geo_rank_media',
                         'six_hour_uid_rank_var',
                         'six_hour_uid_rank_media']
    
    ss4_feature_list_2 = []
    ss4_feature_list_6 = []

    drop_list = ss4_feature_list_1
    drop_list.extend(ss4_feature_list_4)
    #drop_list.extend(cc_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df

def drop_col_KDE_lw(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    lw_feature_list_3 = ['trans_trans_type1_count',
                         'mode_4c3d45ed38eefb7a',
                         'mode_6440f87037199039',
                         'mode_09080b31b40d57e8_num',
                         'mode_9c69742a831d6214_num']

    lw_feature_list_2 = ['entropy_day',
                         'channel_140_num',
                         'amt_src1_a571c7fda8b7df37',
                         'amt_src1_27c42480134c0d02_num',
                         'amt_src1_4d7831c6f695ab19_num',
                         'amt_src1_c5fc631370cabc0d_num',
                         'amt_src1_f29829bc82459191_num',
                         'trans_type1_e0d7b8768da99dd4',
                         'trans_type1_c2f2023d279665b2_num',
                         'op_op_day_nunique',
                         'entropy_op_day',
                         'mode_072eee5c88d380df',
                         'mode_09080b31b40d57e8',
                         'mode_2f3e878175e34d9c',
                         'mode_37031ef728f5c886',
                         'mode_385608c64026c669',
                         'mode_495eeb98eb9b73b8',
                         'mode_4d475374a72edc03',
                         'mode_acfaded7e04e7ba0',
                         'mode_b501fa4fc58206b9',
                         'mode_072eee5c88d380df_num',
                         'mode_270ca3ca8f0d1126_num',
                         'mode_8c7ce5ff939e66d1_num',
                         'mode_8cbc4686cfb509dd_num',
                         'mode_a698c1862f390021_num',
                         'mode_a96a05783c922913_num',
                         'mode_ac63e881c4e19402_num',
                         'mode_acfaded7e04e7ba0_num',
                         'mode_b501fa4fc58206b9_num',
                         'mode_d3c998b9bd4684a8_num',
                         'mode_e1b96d504829cadf_num',
                         'os_102.0',
                         'os_103.0']
    
    lw_feature_list_4 = ['trans_day_count',
                         'trans_day_nunique',
                         'day_1',
                         'day_2',
                         'day_3',
                         'day_4',
                         'day_5',
                         'day_6',
                         'day_7',
                         'day_8',
                         'day_9',
                         'day_10',
                         'day_11',
                         'day_12',
                         'day_13',
                         'day_14',
                         'day_15',
                         'day_16',
                         'day_17',
                         'day_18',
                         'day_19',
                         'day_20',
                         'day_21',
                         'day_22',
                         'day_23',
                         'day_24',
                         'day_25',
                         'day_26',
                         'day_27',
                         'day_28',
                         'day_29',
                         'day_30',
                         'day_1_num',
                         'day_2_num',
                         'day_3_num',
                         'day_4_num',
                         'day_5_num',
                         'day_6_num',
                         'day_7_num',
                         'day_8_num',
                         'day_9_num',
                         'day_10_num',
                         'day_11_num',
                         'day_12_num',
                         'day_13_num',
                         'day_14_num',
                         'day_15_num',
                         'day_16_num',
                         'day_17_num',
                         'day_18_num',
                         'day_19_num',
                         'day_20_num',
                         'day_21_num',
                         'day_22_num',
                         'day_23_num',
                         'day_24_num',
                         'day_25_num',
                         'day_26_num',
                         'day_27_num',
                         'day_28_num',
                         'day_29_num',
                         'day_30_num',
                         'trans_channel_count',
                         'trans_channel_nunique',
                         'channel_119',
                         'channel_141',
                         'entropy_channel',
                         'channel_102_num',
                         'channel_119_num',
                         'channel_141_num',
                         'trans_amt_src1_count',
                         'amt_src1_27c42480134c0d02',
                         'amt_src1_4d7831c6f695ab19',
                         'amt_src1_759979181ba8873c',
                         'amt_src1_8c9987909b3e95a4',
                         'amt_src1_9451ef3c5a0d6807',
                         'amt_src1_992d3ce08a4ca702',
                         'amt_src1_acdbdb842ac20f1e',
                         'amt_src1_d7de70fc65292e41',
                         'amt_src1_155c9e1c32bd0fa2_num',
                         'amt_src1_759979181ba8873c_num',
                         'amt_src1_8c9987909b3e95a4_num',
                         'amt_src1_9451ef3c5a0d6807_num',
                         'amt_src1_992d3ce08a4ca702_num',
                         'amt_src1_acdbdb842ac20f1e_num',
                         'amt_src1_d7de70fc65292e41_num',
                         'trans_type1_0c23319fa2efdd9f',
                         'trans_type1_26bcf43a19df14c8',
                         'trans_type1_6d55c54c8b1056fb',
                         'trans_type1_768160899ae359f6',
                         'trans_type1_a19e7a8951e54c06',
                         'trans_type1_c2f2023d279665b2',
                         'trans_type1_ced62357ad496957',
                         'trans_type1_d0c5bc6f28f5ad35',
                         'trans_type1_fd4d2d1006a95637',
                         'trans_type1_0c23319fa2efdd9f_num',
                         'trans_type1_26bcf43a19df14c8_num',
                         'trans_type1_61bfb66c928f36ac_num',
                         'trans_type1_6d55c54c8b1056fb_num',
                         'trans_type1_768160899ae359f6_num',
                         'trans_type1_d0c5bc6f28f5ad35_num',
                         'trans_type1_fd4d2d1006a95637_num',
                         'op_day_1',
                         'op_day_2',
                         'op_day_3',
                         'op_day_4',
                         'op_day_5',
                         'op_day_6',
                         'op_day_7',
                         'op_day_8',
                         'op_day_9',
                         'op_day_10',
                         'op_day_11',
                         'op_day_12',
                         'op_day_13',
                         'op_day_14',
                         'op_day_15',
                         'op_day_16',
                         'op_day_17',
                         'op_day_18',
                         'op_day_19',
                         'op_day_20',
                         'op_day_21',
                         'op_day_22',
                         'op_day_23',
                         'op_day_24',
                         'op_day_25',
                         'op_day_26',
                         'op_day_27',
                         'op_day_28',
                         'op_day_29',
                         'op_day_30',
                         'op_day_1_num',
                         'op_day_2_num',
                         'op_day_3_num',
                         'op_day_4_num',
                         'op_day_5_num',
                         'op_day_6_num',
                         'op_day_7_num',
                         'op_day_8_num',
                         'op_day_9_num',
                         'op_day_10_num',
                         'op_day_11_num',
                         'op_day_12_num',
                         'op_day_13_num',
                         'op_day_14_num',
                         'op_day_15_num',
                         'op_day_16_num',
                         'op_day_17_num',
                         'op_day_18_num',
                         'op_day_19_num',
                         'op_day_20_num',
                         'op_day_21_num',
                         'op_day_22_num',
                         'op_day_23_num',
                         'op_day_24_num',
                         'op_day_25_num',
                         'op_day_26_num',
                         'op_day_27_num',
                         'op_day_28_num',
                         'op_day_29_num',
                         'op_day_30_num',
                         'op_mode_nunique',
                         'mode_028c7b2172a63a44',
                         'mode_08017d2cb28c2348',
                         'mode_17a6ee1a7b6a02b7',
                         'mode_1c341176507fbd9b',
                         'mode_205ba5de56f834f7',
                         'mode_270ca3ca8f0d1126',
                         'mode_2e6fdb7d4ddef57f',
                         'mode_30fb6b175a9ca918',
                         'mode_3684bb4f59b01fd7',
                         'mode_3f6258f4825c2251',
                         'mode_42a54af5b2d73c77',
                         'mode_43bd7c1135abe71a',
                         'mode_4949910f9a417183',
                         'mode_56624f0cf0173e89',
                         'mode_6216c95d48247735',
                         'mode_680d16190f2d0390',
                         'mode_844de77cbda0a8ee',
                         'mode_84803a9aa001d048',
                         'mode_85481fffc420edca',
                         'mode_8a3ad6c9e44c1659',
                         'mode_8c7ce5ff939e66d1',
                         'mode_9105f3241c9ca194',
                         'mode_9c69742a831d6214',
                         'mode_a698c1862f390021',
                         'mode_ab751225c73ac2bd',
                         'mode_ac63e881c4e19402',
                         'mode_b33675e39153768c',
                         'mode_b668e42707ee9c7b',
                         'mode_bf79b3647c0878eb',
                         'mode_c5bdf60179ae58d7',
                         'mode_d25caee90b27fa9b',
                         'mode_d3c998b9bd4684a8',
                         'mode_da9f055c25d788dc',
                         'mode_e1b96d504829cadf',
                         'mode_e806d126013b42d1',
                         'mode_ead94ed7824d5bf0',
                         'mode_f9cb1243ae2c0b2a',
                         'mode_fc147276b8ff76fb',
                         'entropy_mode',
                         'mode_028c7b2172a63a44_num',
                         'mode_17a6ee1a7b6a02b7_num',
                         'mode_205ba5de56f834f7_num',
                         'mode_2e6fdb7d4ddef57f_num',
                         'mode_30fb6b175a9ca918_num',
                         'mode_3684bb4f59b01fd7_num',
                         'mode_3f6258f4825c2251_num',
                         'mode_42a54af5b2d73c77_num',
                         'mode_43bd7c1135abe71a_num',
                         'mode_4949910f9a417183_num',
                         'mode_56624f0cf0173e89_num',
                         'mode_6216c95d48247735_num',
                         'mode_680d16190f2d0390_num',
                         'mode_844de77cbda0a8ee_num',
                         'mode_84803a9aa001d048_num',
                         'mode_85481fffc420edca_num',
                         'mode_9105f3241c9ca194_num',
                         'mode_963bd8a75ff9ab37_num',
                         'mode_a18c79737c17f4f9_num',
                         'mode_ab751225c73ac2bd_num',
                         'mode_b33675e39153768c_num',
                         'mode_c5bdf60179ae58d7_num',
                         'mode_da9f055c25d788dc_num',
                         'mode_ead94ed7824d5bf0_num',
                         'mode_f9cb1243ae2c0b2a_num',
                         'op_os_nunique',
                         'os_101.0',
                         'os_200.0',
                         'entropy_os',
                         'os_101.0_num',
                         'os_200.0_num']
    
    lw_feature_list_1 = ['trans_type1_a19e7a8951e54c06_num',
                         'trans_type1_ced62357ad496957_num',
                         'trans_type1_e0d7b8768da99dd4_num',
                         'op_op_day_count',
                         'op_mode_count',
                         'mode_8cbc4686cfb509dd',
                         'mode_963bd8a75ff9ab37',
                         'mode_08017d2cb28c2348_num',
                         'mode_1c341176507fbd9b_num',
                         'mode_37031ef728f5c886_num',
                         'mode_385608c64026c669_num',
                         'mode_495eeb98eb9b73b8_num',
                         'mode_4c3d45ed38eefb7a_num',
                         'mode_8a3ad6c9e44c1659_num',
                         'mode_b0d4cd119fbef366_num',
                         'mode_b668e42707ee9c7b_num',
                         'mode_bf79b3647c0878eb_num',
                         'mode_c8741ce15ceac2a4_num',
                         'mode_d25caee90b27fa9b_num',
                         'mode_e806d126013b42d1_num',
                         'mode_fc147276b8ff76fb_num',
                         'op_os_count',
                         'os_102.0_num']
    
    lw_feature_list_5 = []
    
    lw_feature_list_6 = ['amt_src1_4ec06e4d12f8560d',
                         'amt_src1_8c753ae7afb60e61',
                         'amt_src1_b3acdf321be07351',
                         'amt_src1_d46a2a9577fb52c3',
                         'amt_src1_4ec06e4d12f8560d_num',
                         'amt_src1_8c753ae7afb60e61_num',
                         'amt_src1_b3acdf321be07351_num',
                         'amt_src1_d46a2a9577fb52c3_num',
                         'trans_type1_85bced5214d33ad2',
                         'trans_type1_e903cf2a79b83d37',
                         'trans_type1_eb8d10591677bbe1',
                         'trans_type1_85bced5214d33ad2_num',
                         'trans_type1_e903cf2a79b83d37_num',
                         'trans_type1_eb8d10591677bbe1_num',
                         'mode_0e72a7851fadf00b',
                         'mode_1cbe3d31395984d7',
                         'mode_1f287477e8f4b95a',
                         'mode_290ead084a839c02',
                         'mode_2ab549beba0a4482',
                         'mode_30293957fcf5681c',
                         'mode_8bda7a6747b7ad7a',
                         'mode_926aacd05a540d5d',
                         'mode_a18c79737c17f4f9',
                         'mode_a6a93673bd79224c',
                         'mode_ae18d98d880f65bc',
                         'mode_d22abe3bc961e5f2',
                         'mode_d48cfe8d9921f5b6',
                         'mode_da11300b15a56456',
                         'mode_e88d8e8ad8a93013',
                         'mode_f1e83bce32405f92',
                         'mode_f3bdbd82e0d55978',
                         'mode_f4b0872cd482e33f',
                         'mode_1cbe3d31395984d7_num',
                         'mode_1f287477e8f4b95a_num',
                         'mode_290ead084a839c02_num',
                         'mode_2ab549beba0a4482_num',
                         'mode_30293957fcf5681c_num',
                         'mode_8bda7a6747b7ad7a_num',
                         'mode_926aacd05a540d5d_num',
                         'mode_a6a93673bd79224c_num',
                         'mode_ae18d98d880f65bc_num',
                         'mode_d22abe3bc961e5f2_num',
                         'mode_d48cfe8d9921f5b6_num',
                         'mode_e88d8e8ad8a93013_num',
                         'mode_f1e83bce32405f92_num',
                         'mode_f3bdbd82e0d55978_num',
                         'mode_f4b0872cd482e33f_num']

    drop_list = lw_feature_list_1
    drop_list.extend(lw_feature_list_4)
    #drop_list.extend(cc_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df

def drop_col_KDE_ss3(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    ss3_feature_list_4 = ['transac_every_hour_geo_uid_mean',
                         'transac_every_hour_geo_uid_std',
                         'transac_three_hour_geo_rank_max',
                         'transac_three_hour_geo_rank_min',
                         'transac_three_hour_geo_rank_mean',
                         'transac_three_hour_geo_rank_std',
                         'transac_three_hour_geo_rank_media',
                         'transac_six_hour_uid_rank_max',
                         'transac_twelve_hour_uid_rank_media',
                         'transac_day_code1_amt_rank_media']

    ss3_feature_list_5 = ['transac_day_code1_rank_std']
    
    ss3_feature_list_1 = ['transac_day_mechant_rank_var', 'transac_day_mechant_rank_media']
    
    ss3_feature_list_3 = ['transac_every_hour_geo_uid_var',
                         'transac_three_hour_geo_rank_var',
                         'transac_six_hour_uid_rank_min',
                         'transac_six_hour_uid_rank_mean',
                         'transac_six_hour_uid_rank_std',
                         'transac_six_hour_uid_rank_var',
                         'transac_six_hour_uid_rank_media',
                         'transac_twelve_hour_uid_rank_var',
                         'transac_day_mechant_rank_min',
                         'transac_day_code1_rank_min',
                         'transac_day_code1_rank_var',
                         'transac_day_code1_rank_media',
                         'transac_day_code1_amt_rank_max',
                         'transac_day_code1_amt_rank_min',
                         'transac_day_code1_amt_rank_mean',
                         'transac_day_code1_amt_rank_std',
                         'transac_day_code1_amt_rank_var']
    
    ss3_feature_list_2 = []
    
    ss3_feature_list_6 = ['transac_twelve_hour_uid_rank_max',
                         'transac_twelve_hour_uid_rank_min',
                         'transac_twelve_hour_uid_rank_mean',
                         'transac_twelve_hour_uid_rank_std']
    
    

    drop_list = ss3_feature_list_1
    drop_list.extend(ss3_feature_list_4)
    #drop_list.extend(cc_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df
def drop_col_KDE_cc(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    cc_feature_list_4 = ['ver_dev_nui_1d_sum', 'ver_dev_nui_1d_sum_max', 
                     'ver_dev_nui_1d_sum_min', 'ver_dev_nui_3d_sum',
                     'ver_dev_nui_3d_sum_min', 'ver_dev_nui_1h_sum_max', 
                     'ver_dev_nui_1h_sum_min','ver_dev_nui_3d_sum_mean' 
                     ] #需要drop掉的

    cc_feature_list_5 = [] #Green/red overlap
    
    cc_feature_list_1 = ['ver_dev_nui_1d_sum_mean','ver_dev_nui_1h_sum'
                         ,'ver_dev_nui_1h_sum_mean'] #横纵不同
    
    cc_feature_list_3 = ['ver_dev_nui_3d_sum_max']#横轴不同
    
    cc_feature_list_2 = []#纵轴不同

    drop_list = cc_feature_list_1
    drop_list.extend(cc_feature_list_4)
    #drop_list.extend(cc_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df


def drop_col_KDE_ss1(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    ss1_feature_list_4 = ['day_market_ip1_trans_amt_count_std_transac', 'day_market_ip1_sub_trans_amt_count_std_transac',
                      'day_market_device_code2_trans_amt_count_std_transac', 'day_market_device_code1_trans_amt_count_std_transac',
                      'day_market_acc_id1_trans_amt_count_std_transac', 'day_market_ip1_trans_amt_sum_std_transac',
                      'day_market_ip1_sub_trans_amt_sum_std_transac',
                      'day_market_device_code2_trans_amt_sum_std_transac',
                      'day_market_device_code1_trans_amt_sum_std_transac',
                      'day_market_merchant_trans_amt_sum_std_transac',
                      'day_three_hour_market_ip1_trans_amt_sum_max_transac',
                      'day_three_hour_market_ip1_sub_trans_amt_sum_max_transac',
                      'day_three_hour_market_device_code3_trans_amt_sum_max_transac',
                      'day_three_hour_market_merchant_trans_amt_sum_max_transac',
                      'day_three_hour_market_ip1_trans_amt_sum_min_transac',
                      'day_three_hour_market_ip1_sub_trans_amt_sum_min_transac',
                      'day_three_hour_market_merchant_trans_amt_sum_min_transac',
                      'day_three_hour_market_code2_trans_amt_count_min_transac',
                      'day_three_hour_market_ip1_sub_trans_amt_sum_mean_transac',
                      'day_three_hour_market_device_code3_trans_amt_sum_mean_transac',
                      'day_three_hour_market_code2_trans_amt_sum_mean_transac',
                      'day_three_hour_market_acc_id1_trans_amt_count_mean_transac',
                      'day_market_ip1_sub_trans_amt_count_max_transac',
                      'day_market_acc_id1_trans_amt_count_max_transac',
                      'day_market_ip1_trans_amt_sum_max_transac',
                      'day_market_ip1_sub_trans_amt_sum_max_transac',
                      'day_market_acc_id1_trans_amt_sum_max_transac',
                      'day_market_merchant_trans_amt_sum_max_transac',
                      'day_market_ip1_sub_trans_amt_count_min_transac',
                      'day_market_acc_id1_trans_amt_count_min_transac',
                      'day_market_ip1_trans_amt_count_min_transac',
                      'day_market_ip1_trans_amt_sum_min_transac',
                      'day_market_ip1_sub_trans_amt_sum_min_transac',
                      'day_market_code1_trans_amt_sum_min_transac',
                      'day_market_merchant_trans_amt_sum_min_transac',
                      'day_market_code2_trans_amt_count_mean_transac',
                      'day_market_ip1_trans_amt_count_mean_transac',
                      'day_market_ip1_sub_trans_amt_count_mean_transac',
                      'day_market_device_code3_trans_amt_count_mean_transac',
                      'day_market_acc_id1_trans_amt_count_mean_transac',
                      'day_market_ip1_trans_amt_sum_mean_transac',
                      'day_market_ip1_sub_trans_amt_sum_mean_transac',
                      'day_market_mac1_trans_amt_sum_mean_transac',
                      'day_market_device_code3_trans_amt_sum_mean_transac',
                      'day_market_acc_id1_trans_amt_sum_mean_transac',
                      'day_market_code2_trans_amt_sum_mean_transac',
                      'day_market_code1_trans_amt_sum_mean_transac',
                      'day_hour_market_acc_id1_trans_amt_count_mean_transac',
                      'day_hour_market_ip1_trans_amt_sum_mean_transac',
                      'day_hour_market_ip1_sub_trans_amt_sum_mean_transac',
                      'day_hour_acc_id3_mac1_unique_min_transac',
                      'day_hour_acc_id3_device_code2_unique_min_transac',
                      'day_hour_acc_id3_acc_id1_unique_min_transac',
                      'day_hour_market_type_UID_unique_min_transac',
                      'day_hour_market_code_UID_unique_min_transac',
                      'day_hour_trans_type2_UID_unique_min_transac',
                      'day_hour_code1_UID_unique_min_transac',
                      'ip1_sub_acc_id3_UID_unique_min_transac',
                      'ip1_UID_unique_min_transac',
                      'day_hour_code1_device_code3_unique_max_transac',
                      'day_hour_merchant_ip1_unique_max_transac',
                      'day_hour_merchant_device_code2_unique_max_transac',
                      'day_hour_merchant_device_code1_unique_max_transac',
                      'day_hour_amt_src2_UID_unique_max_transac',
                      'day_hour_device1_UID_unique_max_transac',
                      'day_hour_merchant_UID_unique_max_transac',
                      'ip1_sub_acc_id3_UID_unique_max_transac',
                      'ip1_UID_unique_max_transac',
                      'day_hour_acc_id3_acc_id2_unique_mean_transac',
                      'day_hour_acc_id3_device1_unique_mean_transac',
                      'day_hour_code2_acc_id2_unique_mean_transac',
                      'day_hour_code2_device_code3_unique_mean_transac',
                      'day_hour_code1_acc_id2_unique_mean_transac',
                      'day_hour_merchant_device1_unique_mean_transac',
                      'day_hour_merchant_acc_id1_unique_mean_transac',
                      'day_hour_amt_src2_UID_unique_mean_transac',
                      'day_hour_ip1_UID_unique_mean_transac',
                      'day_hour_device1_UID_unique_mean_transac',
                      'day_hour_acc_id1_UID_unique_mean_transac',
                      'ip1_sub_acc_id3_UID_unique_mean_transac',
                      'ip1_UID_unique_mean_transac',
                      'market_code_UID_unique_mean_transac',
                      'device2_UID_unique_mean_transac',
                      'ip2_sub_UID_unique_mean_opera',
                      'day_ip2_geo_code_unique_mean_opera',
                      'day_mac2_geo_code_unique_mean_opera',
                      'day_device_code1_geo_code_unique_mean_opera',
                      'day_device2_geo_code_unique_mean_opera',
                      'day_device1_geo_code_unique_mean_opera',
                      'day_os_geo_code_unique_mean_opera',
                      'day_UID_device2_unique_mean_opera',
                      'day_UID_ip1_sub_unique_mean_opera',
                      'day_UID_device_code2_unique_mean_opera',
                      'day_UID_os_unique_mean_opera',
                      'day_hour_device_code3_UID_unique_mean_opera',
                      'day_hour_device1_UID_unique_mean_opera',
                      'day_hour_UID_device_code2_unique_mean_opera',
                      'day_hour_UID_device2_unique_mean_opera',
                      'day_hour_ip1_sub_geo_code_unique_mean_opera',
                      'day_hour_mac2_geo_code_unique_mean_opera',
                      'day_hour_ip1_geo_code_unique_mean_opera'
                      ]

    ss1_feature_list_5 = ['day_three_hour_market_UID_trans_amt_sum_max_transac',
                         'day_three_hour_market_merchant_trans_amt_sum_mean_transac',
                         'day_market_UID_trans_amt_sum_max_transac',
                         'day_hour_market_code2_trans_amt_sum_mean_transac' 
                         ]#
    ss1_feature_list_1 = ['day_three_hour_market_merchant_trans_amt_sum_std_transac',
                        'day_market_code2_trans_amt_count_std_transac',  'day_market_mac1_trans_amt_count_std_transac',
                        'day_market_device_code3_trans_amt_count_std_transac', 'day_market_UID_trans_amt_count_std_transac',
                        'day_market_device_code3_trans_amt_sum_std_transac', 
                        'day_market_code1_trans_amt_sum_std_transac',
                        'day_three_hour_market_device_code3_trans_amt_sum_min_transac',
                        'day_three_hour_market_acc_id1_trans_amt_count_min_transac',
                        'day_three_hour_market_ip1_trans_amt_count_mean_transac',
                        'day_three_hour_market_ip1_sub_trans_amt_count_mean_transac',
                        'day_market_UID_trans_amt_sum_min_transac', 
                        'day_market_device_code2_trans_amt_count_mean_transac',
                        'day_market_UID_trans_amt_count_mean_transac',
                        'day_market_merchant_trans_amt_sum_mean_transac',
                        'day_hour_market_UID_trans_amt_count_mean_transac',
                        'day_hour_market_device_code3_trans_amt_sum_mean_transac',
                        'day_hour_code2_acc_id1_unique_min_transac',
                        'day_hour_code1_acc_id1_unique_min_transac',
                        'day_hour_geo_code_UID_unique_min_transac',
                        'day_hour_amt_src2_UID_unique_min_transac',
                        'day_hour_device1_UID_unique_min_transac',
                        'day_hour_acc_id1_UID_unique_min_transac',
                        'day_hour_merchant_acc_id1_unique_max_transac',
                        'day_hour_merchant_ip1_unique_mean_transac',
                        'day_hour_merchant_mac1_unique_mean_transac',                    
                        'day_hour_merchant_device_code2_unique_mean_transac',
                        'day_hour_merchant_device_code1_unique_mean_transac',
                        'day_hour_ip1_sub_UID_unique_mean_transac',
                        'day_hour_geo_code_UID_unique_mean_transac',
                        'day_hour_device2_UID_unique_mean_transac',
                        'Hour_mode_UID_success_count_mean_opera',
                        'Hour_mode_UID_count_mean_opera',
                        'mode_UID_success_count_mean_opera',
                        'mode_UID_count_mean_opera',
                        'device2_UID_unique_mean_opera',
                        'device1_UID_unique_mean_opera',
                        'day_ip1_sub_geo_code_unique_mean_opera',
                        'day_ip1_geo_code_unique_mean_opera',
                        'day_hour_geo_code_UID_unique_mean_opera',
                        'day_hour_mac1_UID_unique_mean_opera',
                        'day_hour_device2_UID_unique_mean_opera',
                        'day_hour_device_code2_geo_code_unique_mean_opera',
                        'day_hour_device2_geo_code_unique_mean_opera'
                        ]#分布相同，横纵均不同
    
    ss1_feature_list_3 = ['day_hour_market_merchant_trans_amt_sum_std_transac',
                         'day_market_device_code1_trans_amt_sum_min_transac',
                         'day_market_acc_id1_trans_amt_sum_min_transac',
                         'day_hour_market_merchant_trans_amt_sum_mean_transac',
                         'day_hour_geo_code_UID_unique_max_transac',
                         'day_hour_ip1_sub_UID_unique_mean_opera',
                         'day_hour_mac2_UID_unique_mean_opera',
                         'day_hour_ip1_UID_unique_mean_opera',
                         'day_hour_device_code2_UID_unique_mean_opera',
                         'day_hour_mac1_geo_code_unique_mean_opera',
                         'day_hour_device_code3_geo_code_unique_mean_opera',
                         'day_hour_device1_geo_code_unique_mean_opera',
                         'day_hour_version_geo_code_unique_mean_opera',
                         'day_hour_os_geo_code_unique_mean_opera'
                         ]#分布相同，横轴不同，纵轴相同
    
    ss1_feature_list_2 = ['day_market_mac1_trans_amt_sum_std_transac',
                         'day_market_acc_id1_trans_amt_sum_std_transac',
                         'day_market_UID_trans_amt_sum_std_transac',
                         'day_market_code2_trans_amt_sum_std_transac',
                         'day_three_hour_market_acc_id1_trans_amt_sum_max_transac',
                         'day_three_hour_market_acc_id1_trans_amt_sum_mean_transac',
                         'day_three_hour_market_code1_trans_amt_sum_mean_transac',
                         'day_hour_market_ip1_trans_amt_count_mean_transac',
                         'day_hour_market_ip1_sub_trans_amt_count_mean_transac',
                         'day_hour_market_acc_id1_trans_amt_sum_mean_transac',
                         'day_hour_market_code1_trans_amt_sum_mean_transac',
                         'day_hour_code1_acc_id2_unique_min_transac',                     
                         'day_hour_merchant_UID_unique_mean_transac',
                         'geo_code_UID_unique_min_transac',
                         'geo_code_device1_unique_min_transac',
                         'geo_code_UID_unique_max_transac',
                         'geo_code_device2_unique_max_transac',
                         'geo_code_device1_unique_max_transac',
                         'geo_code_UID_unique_mean_transac',
                         'geo_code_device2_unique_mean_transac',
                         'geo_code_device1_unique_mean_transac',
                         'ip1_sub_UID_unique_mean_opera',
                         'wifi_device2_unique_mean_opera',
                         'wifi_device1_unique_mean_opera',
                         'day_UID_ip1_unique_mean_opera',
                         'day_UID_mac1_unique_mean_opera',
                         'day_hour_ip2_geo_code_unique_mean_opera'
                         ]#分布相同，纵轴不同，横轴相同

    drop_list = ss1_feature_list_1
    drop_list.extend(ss1_feature_list_4)
    #drop_list.extend(ss1_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df

def drop_col_KDE_bb(fea_df):
    '''
    drop掉训练集与测试集 KDE 结果
    '''
    bb_feature_list_1 = ['ip1_subgeo_code_y.1',
                         'ip1_subgeo_code_x.1',
                         'ip1_sub_y.1',
                         'market_typegeo_code_x',
                         'ip1_submerchant_y',
                         'ip1_submerchant_x',
                         'market_typegeo_code_y',
                         'market_typegeo_code_x',
                         'market_typemac1_x',
                         'market_typeip1_x',
                         'market_typeip1_y',
                         'market_typemerchant_y',
                         'market_typemerchant_x',
                         'market_codegeo_code_y',
                         'market_codegeo_code_x',
                         'market_codeip1_x',
                         'market_codemerchant_y',
                         'market_codemerchant_x',
                         'market_code_y',
                         'market_code_x',
                         'trans_type2mac1_y',
                         'trans_type2merchant_y',
                         'trans_type2_x',
                         'geo_codemac1_x.1',
                         'geo_codemerchant_y',
                         'geo_codemerchant_x',
                         'acc_id3geo_code_x',
                         'acc_id3mac1_x',
                         'acc_id3mac1_y',
                         'acc_id2ip1_x',
                         'acc_id2_y',
                         'acc_id2_x',
                         'amt_src2geo_code_x',
                         'amt_src2mac1_x',
                         'amt_src2merchant_y',
                         'amt_src2_x',
                         'balmac1_y.2',
                         'balip1_y.1',
                         'balmerchant_y',
                         'balmerchant_x',
                         'ip1geo_code_y.1',
                         'ip1merchant_y',
                         'ip1merchant_x',
                         'ip1_y.1',
                         'mac1geo_code_y.1',
                         'mac1geo_code_x.1',
                         'mac1merchant_y',
                         'mac1merchant_x',
                         'mac1_y.1',
                         'mac1_x.1',
                         'device2merchant_y',
                         'device2merchant_x',
                         'device1mac1_y.1',
                         'device1merchant_y',
                         'device1merchant_x',
                         'device_code3geo_code_y.1',
                         'device_code3geo_code_x.1',
                         'device_code3merchant_y',
                         'device_code3merchant_x',
                         'device_code3_x.1',
                         'device_code2mac1_x.1',
                         'device_code2ip1_x.1',
                         'device_code2merchant_x',
                         'device_code2_y.1',
                         'device_code2_x.1',
                         'device_code1geo_code_x.1',
                         'device_code1mac1_x.1',
                         'UIDmac1_x',
                         'UIDmac1_y',
                         'UIDmac2_x',
                         'UIDmac2_y',
                         'UIDgeo_code_x',
                         'UIDgeo_code_y',
                         'day_x.2',
                         'dayip1_y',
                         'daymac1_x',
                         'daymac2_x',
                         'daymac2_y',
                         'modemac1_x',
                         'modemac1_y',
                         'modemac2_x',
                         'modemac2_y',
                         'modegeo_code_x',
                         'modegeo_code_y',
                         'successmac1_x',
                         'successmac1_y',
                         'successmac2_x',
                         'successmac2_y',
                         'successgeo_code_x',
                         'timemac1_x',
                         'timemac2_x',
                         'timemac2_y',
                         'timegeo_code_x',
                         'timegeo_code_y',
                         'osip1_y',
                         'osmac1_x',
                         'osmac1_y',
                         'osmac2_x',
                         'osmac2_y',
                         'osgeo_code_x',
                         'osgeo_code_y',
                         'version_y',
                         'versionip1_y',
                         'versionmac1_x',
                         'versionmac2_x',
                         'versionmac2_y',
                         'versiongeo_code_x',
                         'device1ip1_y',
                         'device1mac1_x',
                         'device1mac2_x',
                         'device1geo_code_x',
                         'device2_x',
                         'device2mac2_x',
                         'device2geo_code_x',
                         'device2geo_code_y',
                         'device_code1mac1_x',
                         'device_code1mac1_y',
                         'device_code1mac2_x',
                         'device_code1mac2_y',
                         'device_code1geo_code_x',
                         'device_code1geo_code_y',
                         'device_code2_y',
                         'device_code2mac1_x',
                         'device_code2mac1_y',
                         'device_code2mac2_x',
                         'device_code2mac2_y',
                         'device_code2geo_code_x',
                         'device_code2geo_code_y',
                         'device_code3ip1_x',
                         'mac1_x',
                         'mac1geo_code_x',
                         'mac1geo_code_y',
                         'ip1mac1_x',
                         'ip1mac1_y',
                         'ip1mac2_x',
                         'ip1mac2_y',
                         'wifi_y',
                         'wifiip1_x',
                         'wifiip1_y',
                         'wifimac1_y',
                         'wifimac2_x',
                         'wifimac2_y',
                         'wifigeo_code_x',
                         'wifigeo_code_y',
                         'geo_code_x',
                         'geo_codemac1_y',
                         'geo_codemac2_x',
                         'geo_codemac2_y',
                         'ip1_sub_x',
                         'ip1_subip1_y',
                         'ip1_submac1_x',
                         'ip1_submac1_y',
                         'ip1_submac2_x',
                         'ip1_submac2_y',
                         'ip1_subgeo_code_x',
                         'channel_x',
                         'channelmerchant_x',
                         'channelmerchant_y',
                         'channelip1_y',
                         'channelmac1_x',
                         'channelmac1_y',
                         'channelgeo_code_x',
                         'day_y.3',
                         'day_y.5',
                         'daymerchant_x',
                         'dayip1_x.4',
                         'daymac1_y.3',
                         'time_x.1',
                         'time_y.1',
                         'timemerchant_x',
                         'timemac1_x.1',
                         'timemac1_y.1',
                         'trans_amt_x',
                         'trans_amt_y',
                         'trans_amt_x.1',
                         'trans_amt_x.2',
                         'trans_amtmerchant_x',
                         'trans_amtmerchant',
                         'trans_amtip1_x.1',
                         'trans_amtip1_y.1',
                         'trans_amtip1_y.2',
                         'trans_amtip1',
                         'trans_amtmac1_x',
                         'trans_amtmac1_y',
                         'amt_src1_x',
                         'amt_src1merchant_x',
                         'amt_src1merchant_y',
                         'amt_src1mac1_x',
                         'merchantmac1_x',
                         'merchantmac1_y',
                         'merchantgeo_code_y',
                         'code1ip1_x',
                         'code1ip1_y',
                         'code1mac1_x',
                         'code1geo_code_x',
                         'code1geo_code_y',
                         'code2_y',
                         'trans_type1_x',
                         'trans_type1merchant_x',
                         'trans_type1merchant_y',
                         'trans_type1ip1_y',
                         'trans_type1mac1_x',
                         'acc_id1_x',
                         'device_code1_y.1',
                         'device_code1merchant_x',
                         'device_code1merchant_y']

    bb_feature_list_2 = ['market_type_y',
                         'trans_type2mac1_y',
                         'trans_type2ip1_y',
                         'acc_id3_x',
                         'balip1_y.2',
                         'bal',
                         'bal_y.2',
                         'bal_x.1',
                         'day_x',
                         'day_y',
                         'day_y.1',
                         'day_x.3',
                         'dayip1_x.3',
                         'daymac1_x.1',
                         'daymac1_y.1',
                         'daymac1_y.2',
                         'daymac1_x.3',
                         'daymac2_x.1',
                         'daymac2_y.1',
                         'daymac2_y.2',
                         'mode_x',
                         'mode_y',
                         'success_x',
                         'success_y',
                         'successgeo_code_y',
                         'time_x',
                         'time_y',
                         'os_x',
                         'version_x',
                         'device1_x',
                         'device_code1_x',
                         'device_code3_x',
                         'device_code3geo_code_x',
                         'device_code3geo_code_y',
                         'ip1_x',
                         'wifimac1_x',
                         'ip1_subgeo_code_y',
                         'channel_y',
                         'day_x.4',
                         'day_y.6',
                         'daymerchant_x.1',
                         'daymerchant_y.1',
                         'daymerchant',
                         'dayip1_y.6',
                         'daymac1_y.4',
                         'daymac1_x.5',
                         'timemerchant_y',
                         'device_code1_x.1']
    
    bb_feature_list_3 = ['ip1_subip1_y.1',
                         'ip1_submac1_x.1',
                         'ip1_sub_x.1',
                         'market_typemac1_y',
                         'market_codemac1_y',
                         'market_codemac1_x',
                         'market_codeip1_y',
                         'trans_type2merchant_x',
                         'acc_id3merchant_x',
                         'acc_id3_y',
                         'acc_id2geo_code_y',
                         'acc_id2mac1_x',
                         'acc_id2mac1_y',
                         'acc_id2merchant_y',
                         'acc_id2merchant_x',
                         'amt_src2merchant_x',
                         'balmac1_x.2',
                         'balmac1_y',
                         'balmac1_x',
                         'ip1mac1_y.1',
                         'ip1mac1_x.1',
                         'ip1_x.1',
                         'mac1ip1_x.1',
                         'device2mac1_y.1',
                         'device2mac1_x.1',
                         'device2_x.1',
                         'device1mac1_x.1',
                         'device1_y.1',
                         'device1_x.1',
                         'device_code3ip1_y.1',
                         'device_code1ip1_x.1',
                         'daymac1_y',
                         'daymac2_x.2',
                         'timemac1_y',
                         'versionmac1_y',
                         'device1mac1_y',
                         'device1mac2_y',
                         'device2mac1_x',
                         'device2mac1_y',
                         'device2mac2_y',
                         'device_code2_x',
                         'device_code3mac2_y',
                         'mac1ip1_x',
                         'mac2_x',
                         'geo_code_y',
                         'geo_codemac1_x',
                         'channelgeo_code_y',
                         'day_x.6',
                         'daymerchant_y',
                         'daymerchant_x.2',
                         'daymac1_x.4',
                         'daymac1_y.5',
                         'trans_amtip1_x.2',
                         'trans_amtmac1_x.1',
                         'trans_amtmac1_x.2',
                         'trans_amtmac1_y.2',
                         'trans_amtmac1',
                         'amt_src1mac1_y',
                         'amt_src1geo_code_y',
                         'acc_id1merchant_x',
                         'acc_id1merchant_y']
    
    bb_feature_list_4 = ['ip1_subip1_x.1',
                         'market_type_x',
                         'trans_type2geo_code_x',
                         'trans_type2ip1_x',
                         'geo_codeip1_y.1',
                         'geo_codeip1_y.1',
                         'geo_code_y.1',
                         'acc_id2geo_code_x',
                         'acc_id2ip1_y',
                         'amt_src2ip1_x',
                         'balmac1',
                         'balmac1_y.1',
                         'balip1_x.2',
                         'balip1_x.1',
                         'balip1_y',
                         'balip1_x',
                         'balmerchant',
                         'balmerchant_y.2',
                         'balmerchant_x.2',
                         'balmerchant_y.1',
                         'balmerchant_x.1',
                         'bal_x.2',
                         'bal_y.1',
                         'bal_y',
                         'bal_x',
                         'ip1geo_code_x.1',
                         'mac1ip1_y.1',
                         'device2geo_code_y.1',
                         'device2geo_code_x.1',
                         'device2ip1_y.1',
                         'device2ip1_x.1',
                         'device2_y.1',
                         'device1geo_code_y.1',
                         'device1geo_code_x.1',
                         'device1ip1_y.1',
                         'device_code3mac1_y.1',
                         'device_code3mac1_x.1',
                         'device_code3ip1_x.1',
                         'device_code3_y.1',
                         'device_code2geo_code_y.1',
                         'device_code2geo_code_x.1',
                         'device_code2ip1_y.1',
                         'device_code2merchant_y',
                         'device_code1geo_code_y.1',
                         'device_code1ip1_y.1',
                         'UID',
                         'UIDip1_x',
                         'UIDip1_y',
                         'day_x.1',
                         'day_y.2',
                         'dayip1_x',
                         'dayip1_x.1',
                         'dayip1_y.1',
                         'dayip1_x.2',
                         'dayip1_y.2',
                         'daymac1_x.2',
                         'modeip1_x',
                         'successip1_x',
                         'timeip1_x',
                         'timeip1_y',
                         'os_y',
                         'osip1_x',
                         'versionip1_x',
                         'device1ip1_x',
                         'device2ip1_x',
                         'device2ip1_y',
                         'device_code1_y',
                         'device_code1ip1_x',
                         'device_code1ip1_y',
                         'device_code2ip1_x',
                         'device_code2ip1_y',
                         'device_code3_y',
                         'device_code3ip1_y',
                         'device_code3mac1_x',
                         'device_code3mac1_y',
                         'device_code3mac2_x',
                         'mac1_y',
                         'mac1ip1_y',
                         'mac1mac2_x',
                         'mac1mac2_y',
                         'mac2_y',
                         'mac2ip1_x',
                         'mac2ip1_y',
                         'mac2mac1_x',
                         'mac2mac1_y',
                         'mac2geo_code_x',
                         'mac2geo_code_y',
                         'ip1geo_code_x',
                         'ip1geo_code_y',
                         'ip2_x',
                         'ip2_y',
                         'ip2ip1_x',
                         'ip2ip1_y',
                         'geo_codeip1_x',
                         'geo_codeip1_y',
                         'ip1_subip1_x',
                         'ip2_sub_x',
                         'ip2_sub_y',
                         'ip2_subip1_x',
                         'ip2_subip1_y',
                         'channelip1_x',
                         'day_y.4',
                         'day_x.5',
                         'daymerchant_y.2',
                         'dayip1_y.3',
                         'dayip1_y.4',
                         'dayip1_x.5',
                         'dayip1_y.5',
                         'dayip1_x.6',
                         'timeip1_x.1',
                         'timeip1_y.1',
                         'timegeo_code_x.1',
                         'timegeo_code_y.1',
                         'trans_amt_y.1',
                         'trans_amt_y.2',
                         'trans_amtmerchant_y.1',
                         'trans_amtmerchant_x.2',
                         'trans_amtmerchant_y.2',
                         'trans_amtip1_x',
                         'trans_amtip1_y',
                         'amt_src1ip1_x',
                         'amt_src1geo_code_x',
                         'merchant_x',
                         'merchant_y',
                         'merchantip1_x',
                         'merchantip1_y',
                         'merchantgeo_code_x',
                         'code1_x',
                         'code1_y',
                         'code1merchant_x',
                         'code1merchant_y',
                         'code2_x',
                         'code2merchant_x',
                         'code2merchant_y',
                         'trans_type1ip1_x',
                         'trans_type1geo_code_x',
                         'acc_id1_y',
                         'acc_id1ip1_x',
                         'acc_id1ip1_y',
                         'acc_id1geo_code_x',
                         'acc_id1geo_code_y']
    
    bb_feature_list_5 = ['daymac2',
                         'modeip1_y',
                         'successip1_y',
                         'device1_y',
                         'ip2mac1_x',
                         'ip2mac1_y',
                         'ip2mac2_x',
                         'ip2mac2_y',
                         'ip2geo_code_x',
                         'ip2geo_code_y',
                         'ip2_submac1_x',
                         'ip2_submac1_y',
                         'ip2_submac2_x',
                         'ip2_submac2_y',
                         'ip2_subgeo_code_x',
                         'ip2_subgeo_code_y',
                         'code2ip1_x',
                         'code2ip1_y',
                         'code2mac1_x',
                         'code2mac1_y',
                         'code2geo_code_x',
                         'code2geo_code_y']

    drop_list = bb_feature_list_1
    drop_list.extend(bb_feature_list_4)
    #drop_list.extend(bb_feature_list_5)
    #drop_list.extend(bb_drop_list_3)
    for col in list(fea_df.columns):
        if col in drop_list:
            fea_df = fea_df.drop([col], axis=1)
    
    return fea_df

